
        /* eslint-disable */
        module.exports = function(Blockly){
          Blockly.Blocks={};// Do not edit this file; automatically generated by build.py.
'use strict';

goog.provide("Blockly");
goog.provide("Blockly.Blocks");

goog.provide("Blockly.Blocks.colour");
goog.provide("Blockly.Constants.Colour");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.Colour.HUE = 20;
Blockly.defineBlocksWithJsonArray([{"type":"colour_picker", "message0":"%1", "args0":[{"type":"field_colour", "name":"COLOUR", "colour":"#ff0000"}], "output":"Colour", "helpUrl":"%{BKY_COLOUR_PICKER_HELPURL}", "style":"colour_blocks", "tooltip":"%{BKY_COLOUR_PICKER_TOOLTIP}", "extensions":["parent_tooltip_when_inline"]}, {"type":"colour_random", "message0":"%{BKY_COLOUR_RANDOM_TITLE}", "output":"Colour", "helpUrl":"%{BKY_COLOUR_RANDOM_HELPURL}", "style":"colour_blocks", "tooltip":"%{BKY_COLOUR_RANDOM_TOOLTIP}"}, 
{"type":"colour_rgb", "message0":"%{BKY_COLOUR_RGB_TITLE} %{BKY_COLOUR_RGB_RED} %1 %{BKY_COLOUR_RGB_GREEN} %2 %{BKY_COLOUR_RGB_BLUE} %3", "args0":[{"type":"input_value", "name":"RED", "check":"Number", "align":"RIGHT"}, {"type":"input_value", "name":"GREEN", "check":"Number", "align":"RIGHT"}, {"type":"input_value", "name":"BLUE", "check":"Number", "align":"RIGHT"}], "output":"Colour", "helpUrl":"%{BKY_COLOUR_RGB_HELPURL}", "style":"colour_blocks", "tooltip":"%{BKY_COLOUR_RGB_TOOLTIP}"}, {"type":"colour_blend", 
"message0":"%{BKY_COLOUR_BLEND_TITLE} %{BKY_COLOUR_BLEND_COLOUR1} " + "%1 %{BKY_COLOUR_BLEND_COLOUR2} %2 %{BKY_COLOUR_BLEND_RATIO} %3", "args0":[{"type":"input_value", "name":"COLOUR1", "check":"Colour", "align":"RIGHT"}, {"type":"input_value", "name":"COLOUR2", "check":"Colour", "align":"RIGHT"}, {"type":"input_value", "name":"RATIO", "check":"Number", "align":"RIGHT"}], "output":"Colour", "helpUrl":"%{BKY_COLOUR_BLEND_HELPURL}", "style":"colour_blocks", "tooltip":"%{BKY_COLOUR_BLEND_TOOLTIP}"}]);
goog.provide("Blockly.Blocks.lists");
goog.provide("Blockly.Constants.Lists");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.Lists.HUE = 260;
Blockly.defineBlocksWithJsonArray([{"type":"lists_create_empty", "message0":"%{BKY_LISTS_CREATE_EMPTY_TITLE}", "output":"Array", "style":"list_blocks", "tooltip":"%{BKY_LISTS_CREATE_EMPTY_TOOLTIP}", "helpUrl":"%{BKY_LISTS_CREATE_EMPTY_HELPURL}"}, {"type":"lists_repeat", "message0":"%{BKY_LISTS_REPEAT_TITLE}", "args0":[{"type":"input_value", "name":"ITEM"}, {"type":"input_value", "name":"NUM", "check":"Number"}], "output":"Array", "style":"list_blocks", "tooltip":"%{BKY_LISTS_REPEAT_TOOLTIP}", "helpUrl":"%{BKY_LISTS_REPEAT_HELPURL}"}, 
{"type":"lists_reverse", "message0":"%{BKY_LISTS_REVERSE_MESSAGE0}", "args0":[{"type":"input_value", "name":"LIST", "check":"Array"}], "output":"Array", "inputsInline":true, "style":"list_blocks", "tooltip":"%{BKY_LISTS_REVERSE_TOOLTIP}", "helpUrl":"%{BKY_LISTS_REVERSE_HELPURL}"}, {"type":"lists_isEmpty", "message0":"%{BKY_LISTS_ISEMPTY_TITLE}", "args0":[{"type":"input_value", "name":"VALUE", "check":["String", "Array"]}], "output":"Boolean", "style":"list_blocks", "tooltip":"%{BKY_LISTS_ISEMPTY_TOOLTIP}", 
"helpUrl":"%{BKY_LISTS_ISEMPTY_HELPURL}"}, {"type":"lists_length", "message0":"%{BKY_LISTS_LENGTH_TITLE}", "args0":[{"type":"input_value", "name":"VALUE", "check":["String", "Array"]}], "output":"Number", "style":"list_blocks", "tooltip":"%{BKY_LISTS_LENGTH_TOOLTIP}", "helpUrl":"%{BKY_LISTS_LENGTH_HELPURL}"}]);
Blockly.Blocks["lists_create_with"] = {init:function() {
  this.setHelpUrl(Blockly.Msg["LISTS_CREATE_WITH_HELPURL"]);
  this.setStyle("list_blocks");
  this.itemCount_ = 3;
  this.updateShape_();
  this.setOutput(true, "Array");
  this.setMutator(new Blockly.Mutator(["lists_create_with_item"]));
  this.setTooltip(Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"]);
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("items", this.itemCount_);
  return container;
}, domToMutation:function(xmlElement) {
  this.itemCount_ = parseInt(xmlElement.getAttribute("items"), 10);
  this.updateShape_();
}, decompose:function(workspace) {
  var containerBlock = workspace.newBlock("lists_create_with_container");
  containerBlock.initSvg();
  var connection = containerBlock.getInput("STACK").connection;
  for (var i = 0; i < this.itemCount_; i++) {
    var itemBlock = workspace.newBlock("lists_create_with_item");
    itemBlock.initSvg();
    connection.connect(itemBlock.previousConnection);
    connection = itemBlock.nextConnection;
  }
  return containerBlock;
}, compose:function(containerBlock) {
  var itemBlock = containerBlock.getInputTargetBlock("STACK");
  var connections = [];
  while (itemBlock) {
    connections.push(itemBlock.valueConnection_);
    itemBlock = itemBlock.nextConnection && itemBlock.nextConnection.targetBlock();
  }
  for (var i = 0; i < this.itemCount_; i++) {
    var connection = this.getInput("ADD" + i).connection.targetConnection;
    if (connection && connections.indexOf(connection) == -1) {
      connection.disconnect();
    }
  }
  this.itemCount_ = connections.length;
  this.updateShape_();
  for (var i = 0; i < this.itemCount_; i++) {
    Blockly.Mutator.reconnect(connections[i], this, "ADD" + i);
  }
}, saveConnections:function(containerBlock) {
  var itemBlock = containerBlock.getInputTargetBlock("STACK");
  var i = 0;
  while (itemBlock) {
    var input = this.getInput("ADD" + i);
    itemBlock.valueConnection_ = input && input.connection.targetConnection;
    i++;
    itemBlock = itemBlock.nextConnection && itemBlock.nextConnection.targetBlock();
  }
}, updateShape_:function() {
  if (this.itemCount_ && this.getInput("EMPTY")) {
    this.removeInput("EMPTY");
  } else {
    if (!this.itemCount_ && !this.getInput("EMPTY")) {
      this.appendDummyInput("EMPTY").appendField(Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"]);
    }
  }
  for (var i = 0; i < this.itemCount_; i++) {
    if (!this.getInput("ADD" + i)) {
      var input = this.appendValueInput("ADD" + i);
      if (i == 0) {
        input.appendField(Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"]);
      }
    }
  }
  while (this.getInput("ADD" + i)) {
    this.removeInput("ADD" + i);
    i++;
  }
}};
Blockly.Blocks["lists_create_with_container"] = {init:function() {
  this.setStyle("list_blocks");
  this.appendDummyInput().appendField(Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"]);
  this.appendStatementInput("STACK");
  this.setTooltip(Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"]);
  this.contextMenu = false;
}};
Blockly.Blocks["lists_create_with_item"] = {init:function() {
  this.setStyle("list_blocks");
  this.appendDummyInput().appendField(Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"]);
  this.setPreviousStatement(true);
  this.setNextStatement(true);
  this.setTooltip(Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"]);
  this.contextMenu = false;
}};
Blockly.Blocks["lists_indexOf"] = {init:function() {
  var OPERATORS = [[Blockly.Msg["LISTS_INDEX_OF_FIRST"], "FIRST"], [Blockly.Msg["LISTS_INDEX_OF_LAST"], "LAST"]];
  this.setHelpUrl(Blockly.Msg["LISTS_INDEX_OF_HELPURL"]);
  this.setStyle("list_blocks");
  this.setOutput(true, "Number");
  this.appendValueInput("VALUE").setCheck("Array").appendField(Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"]);
  this.appendValueInput("FIND").appendField(new Blockly.FieldDropdown(OPERATORS), "END");
  this.setInputsInline(true);
  var thisBlock = this;
  this.setTooltip(function() {
    return Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"].replace("%1", thisBlock.workspace.options.oneBasedIndex ? "0" : "-1");
  });
}};
Blockly.Blocks["lists_getIndex"] = {init:function() {
  var MODE = [[Blockly.Msg["LISTS_GET_INDEX_GET"], "GET"], [Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"], "GET_REMOVE"], [Blockly.Msg["LISTS_GET_INDEX_REMOVE"], "REMOVE"]];
  this.WHERE_OPTIONS = [[Blockly.Msg["LISTS_GET_INDEX_FROM_START"], "FROM_START"], [Blockly.Msg["LISTS_GET_INDEX_FROM_END"], "FROM_END"], [Blockly.Msg["LISTS_GET_INDEX_FIRST"], "FIRST"], [Blockly.Msg["LISTS_GET_INDEX_LAST"], "LAST"], [Blockly.Msg["LISTS_GET_INDEX_RANDOM"], "RANDOM"]];
  this.setHelpUrl(Blockly.Msg["LISTS_GET_INDEX_HELPURL"]);
  this.setStyle("list_blocks");
  var modeMenu = new Blockly.FieldDropdown(MODE, function(value) {
    var isStatement = value == "REMOVE";
    this.sourceBlock_.updateStatement_(isStatement);
  });
  this.appendValueInput("VALUE").setCheck("Array").appendField(Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"]);
  this.appendDummyInput().appendField(modeMenu, "MODE").appendField("", "SPACE");
  this.appendDummyInput("AT");
  if (Blockly.Msg["LISTS_GET_INDEX_TAIL"]) {
    this.appendDummyInput("TAIL").appendField(Blockly.Msg["LISTS_GET_INDEX_TAIL"]);
  }
  this.setInputsInline(true);
  this.setOutput(true);
  this.updateAt_(true);
  var thisBlock = this;
  this.setTooltip(function() {
    var mode = thisBlock.getFieldValue("MODE");
    var where = thisBlock.getFieldValue("WHERE");
    var tooltip = "";
    switch(mode + " " + where) {
      case "GET FROM_START":
      case "GET FROM_END":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"];
        break;
      case "GET FIRST":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"];
        break;
      case "GET LAST":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"];
        break;
      case "GET RANDOM":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"];
        break;
      case "GET_REMOVE FROM_START":
      case "GET_REMOVE FROM_END":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"];
        break;
      case "GET_REMOVE FIRST":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"];
        break;
      case "GET_REMOVE LAST":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"];
        break;
      case "GET_REMOVE RANDOM":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"];
        break;
      case "REMOVE FROM_START":
      case "REMOVE FROM_END":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"];
        break;
      case "REMOVE FIRST":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"];
        break;
      case "REMOVE LAST":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"];
        break;
      case "REMOVE RANDOM":
        tooltip = Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"];
        break;
    }
    if (where == "FROM_START" || where == "FROM_END") {
      var msg = where == "FROM_START" ? Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] : Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"];
      tooltip += "  " + msg.replace("%1", thisBlock.workspace.options.oneBasedIndex ? "#1" : "#0");
    }
    return tooltip;
  });
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  var isStatement = !this.outputConnection;
  container.setAttribute("statement", isStatement);
  var isAt = this.getInput("AT").type == Blockly.INPUT_VALUE;
  container.setAttribute("at", isAt);
  return container;
}, domToMutation:function(xmlElement) {
  var isStatement = xmlElement.getAttribute("statement") == "true";
  this.updateStatement_(isStatement);
  var isAt = xmlElement.getAttribute("at") != "false";
  this.updateAt_(isAt);
}, updateStatement_:function(newStatement) {
  var oldStatement = !this.outputConnection;
  if (newStatement != oldStatement) {
    this.unplug(true, true);
    if (newStatement) {
      this.setOutput(false);
      this.setPreviousStatement(true);
      this.setNextStatement(true);
    } else {
      this.setPreviousStatement(false);
      this.setNextStatement(false);
      this.setOutput(true);
    }
  }
}, updateAt_:function(isAt) {
  this.removeInput("AT");
  this.removeInput("ORDINAL", true);
  if (isAt) {
    this.appendValueInput("AT").setCheck("Number");
    if (Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]) {
      this.appendDummyInput("ORDINAL").appendField(Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]);
    }
  } else {
    this.appendDummyInput("AT");
  }
  var menu = new Blockly.FieldDropdown(this.WHERE_OPTIONS, function(value) {
    var newAt = value == "FROM_START" || value == "FROM_END";
    if (newAt != isAt) {
      var block = this.sourceBlock_;
      block.updateAt_(newAt);
      block.setFieldValue(value, "WHERE");
      return null;
    }
    return undefined;
  });
  this.getInput("AT").appendField(menu, "WHERE");
  if (Blockly.Msg["LISTS_GET_INDEX_TAIL"]) {
    this.moveInputBefore("TAIL", null);
  }
}};
Blockly.Blocks["lists_setIndex"] = {init:function() {
  var MODE = [[Blockly.Msg["LISTS_SET_INDEX_SET"], "SET"], [Blockly.Msg["LISTS_SET_INDEX_INSERT"], "INSERT"]];
  this.WHERE_OPTIONS = [[Blockly.Msg["LISTS_GET_INDEX_FROM_START"], "FROM_START"], [Blockly.Msg["LISTS_GET_INDEX_FROM_END"], "FROM_END"], [Blockly.Msg["LISTS_GET_INDEX_FIRST"], "FIRST"], [Blockly.Msg["LISTS_GET_INDEX_LAST"], "LAST"], [Blockly.Msg["LISTS_GET_INDEX_RANDOM"], "RANDOM"]];
  this.setHelpUrl(Blockly.Msg["LISTS_SET_INDEX_HELPURL"]);
  this.setStyle("list_blocks");
  this.appendValueInput("LIST").setCheck("Array").appendField(Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"]);
  this.appendDummyInput().appendField(new Blockly.FieldDropdown(MODE), "MODE").appendField("", "SPACE");
  this.appendDummyInput("AT");
  this.appendValueInput("TO").appendField(Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"]);
  this.setInputsInline(true);
  this.setPreviousStatement(true);
  this.setNextStatement(true);
  this.setTooltip(Blockly.Msg["LISTS_SET_INDEX_TOOLTIP"]);
  this.updateAt_(true);
  var thisBlock = this;
  this.setTooltip(function() {
    var mode = thisBlock.getFieldValue("MODE");
    var where = thisBlock.getFieldValue("WHERE");
    var tooltip = "";
    switch(mode + " " + where) {
      case "SET FROM_START":
      case "SET FROM_END":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"];
        break;
      case "SET FIRST":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"];
        break;
      case "SET LAST":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"];
        break;
      case "SET RANDOM":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"];
        break;
      case "INSERT FROM_START":
      case "INSERT FROM_END":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"];
        break;
      case "INSERT FIRST":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"];
        break;
      case "INSERT LAST":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"];
        break;
      case "INSERT RANDOM":
        tooltip = Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"];
        break;
    }
    if (where == "FROM_START" || where == "FROM_END") {
      tooltip += "  " + Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"].replace("%1", thisBlock.workspace.options.oneBasedIndex ? "#1" : "#0");
    }
    return tooltip;
  });
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  var isAt = this.getInput("AT").type == Blockly.INPUT_VALUE;
  container.setAttribute("at", isAt);
  return container;
}, domToMutation:function(xmlElement) {
  var isAt = xmlElement.getAttribute("at") != "false";
  this.updateAt_(isAt);
}, updateAt_:function(isAt) {
  this.removeInput("AT");
  this.removeInput("ORDINAL", true);
  if (isAt) {
    this.appendValueInput("AT").setCheck("Number");
    if (Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]) {
      this.appendDummyInput("ORDINAL").appendField(Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]);
    }
  } else {
    this.appendDummyInput("AT");
  }
  var menu = new Blockly.FieldDropdown(this.WHERE_OPTIONS, function(value) {
    var newAt = value == "FROM_START" || value == "FROM_END";
    if (newAt != isAt) {
      var block = this.sourceBlock_;
      block.updateAt_(newAt);
      block.setFieldValue(value, "WHERE");
      return null;
    }
    return undefined;
  });
  this.moveInputBefore("AT", "TO");
  if (this.getInput("ORDINAL")) {
    this.moveInputBefore("ORDINAL", "TO");
  }
  this.getInput("AT").appendField(menu, "WHERE");
}};
Blockly.Blocks["lists_getSublist"] = {init:function() {
  this["WHERE_OPTIONS_1"] = [[Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"], "FROM_START"], [Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"], "FROM_END"], [Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"], "FIRST"]];
  this["WHERE_OPTIONS_2"] = [[Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"], "FROM_START"], [Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"], "FROM_END"], [Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"], "LAST"]];
  this.setHelpUrl(Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"]);
  this.setStyle("list_blocks");
  this.appendValueInput("LIST").setCheck("Array").appendField(Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"]);
  this.appendDummyInput("AT1");
  this.appendDummyInput("AT2");
  if (Blockly.Msg["LISTS_GET_SUBLIST_TAIL"]) {
    this.appendDummyInput("TAIL").appendField(Blockly.Msg["LISTS_GET_SUBLIST_TAIL"]);
  }
  this.setInputsInline(true);
  this.setOutput(true, "Array");
  this.updateAt_(1, true);
  this.updateAt_(2, true);
  this.setTooltip(Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"]);
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  var isAt1 = this.getInput("AT1").type == Blockly.INPUT_VALUE;
  container.setAttribute("at1", isAt1);
  var isAt2 = this.getInput("AT2").type == Blockly.INPUT_VALUE;
  container.setAttribute("at2", isAt2);
  return container;
}, domToMutation:function(xmlElement) {
  var isAt1 = xmlElement.getAttribute("at1") == "true";
  var isAt2 = xmlElement.getAttribute("at2") == "true";
  this.updateAt_(1, isAt1);
  this.updateAt_(2, isAt2);
}, updateAt_:function(n, isAt) {
  this.removeInput("AT" + n);
  this.removeInput("ORDINAL" + n, true);
  if (isAt) {
    this.appendValueInput("AT" + n).setCheck("Number");
    if (Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]) {
      this.appendDummyInput("ORDINAL" + n).appendField(Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]);
    }
  } else {
    this.appendDummyInput("AT" + n);
  }
  var menu = new Blockly.FieldDropdown(this["WHERE_OPTIONS_" + n], function(value) {
    var newAt = value == "FROM_START" || value == "FROM_END";
    if (newAt != isAt) {
      var block = this.sourceBlock_;
      block.updateAt_(n, newAt);
      block.setFieldValue(value, "WHERE" + n);
      return null;
    }
    return undefined;
  });
  this.getInput("AT" + n).appendField(menu, "WHERE" + n);
  if (n == 1) {
    this.moveInputBefore("AT1", "AT2");
    if (this.getInput("ORDINAL1")) {
      this.moveInputBefore("ORDINAL1", "AT2");
    }
  }
  if (Blockly.Msg["LISTS_GET_SUBLIST_TAIL"]) {
    this.moveInputBefore("TAIL", null);
  }
}};
Blockly.Blocks["lists_sort"] = {init:function() {
  this.jsonInit({"message0":Blockly.Msg["LISTS_SORT_TITLE"], "args0":[{"type":"field_dropdown", "name":"TYPE", "options":[[Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"], "NUMERIC"], [Blockly.Msg["LISTS_SORT_TYPE_TEXT"], "TEXT"], [Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"], "IGNORE_CASE"]]}, {"type":"field_dropdown", "name":"DIRECTION", "options":[[Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"], "1"], [Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"], "-1"]]}, {"type":"input_value", "name":"LIST", "check":"Array"}], 
  "output":"Array", "style":"list_blocks", "tooltip":Blockly.Msg["LISTS_SORT_TOOLTIP"], "helpUrl":Blockly.Msg["LISTS_SORT_HELPURL"]});
}};
Blockly.Blocks["lists_split"] = {init:function() {
  var thisBlock = this;
  var dropdown = new Blockly.FieldDropdown([[Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"], "SPLIT"], [Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"], "JOIN"]], function(newMode) {
    thisBlock.updateType_(newMode);
  });
  this.setHelpUrl(Blockly.Msg["LISTS_SPLIT_HELPURL"]);
  this.setStyle("list_blocks");
  this.appendValueInput("INPUT").setCheck("String").appendField(dropdown, "MODE");
  this.appendValueInput("DELIM").setCheck("String").appendField(Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"]);
  this.setInputsInline(true);
  this.setOutput(true, "Array");
  this.setTooltip(function() {
    var mode = thisBlock.getFieldValue("MODE");
    if (mode == "SPLIT") {
      return Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"];
    } else {
      if (mode == "JOIN") {
        return Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"];
      }
    }
    throw Error("Unknown mode: " + mode);
  });
}, updateType_:function(newMode) {
  if (newMode == "SPLIT") {
    this.outputConnection.setCheck("Array");
    this.getInput("INPUT").setCheck("String");
  } else {
    this.outputConnection.setCheck("String");
    this.getInput("INPUT").setCheck("Array");
  }
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("mode", this.getFieldValue("MODE"));
  return container;
}, domToMutation:function(xmlElement) {
  this.updateType_(xmlElement.getAttribute("mode"));
}};
goog.provide("Blockly.Blocks.logic");
goog.provide("Blockly.Constants.Logic");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.Logic.HUE = 210;
Blockly.defineBlocksWithJsonArray([{"type":"logic_boolean", "message0":"%1", "args0":[{"type":"field_dropdown", "name":"BOOL", "options":[["%{BKY_LOGIC_BOOLEAN_TRUE}", "TRUE"], ["%{BKY_LOGIC_BOOLEAN_FALSE}", "FALSE"]]}], "output":"Boolean", "style":"logic_blocks", "tooltip":"%{BKY_LOGIC_BOOLEAN_TOOLTIP}", "helpUrl":"%{BKY_LOGIC_BOOLEAN_HELPURL}"}, {"type":"controls_if", "message0":"%{BKY_CONTROLS_IF_MSG_IF} %1", "args0":[{"type":"input_value", "name":"IF0", "check":"Boolean"}], "message1":"%{BKY_CONTROLS_IF_MSG_THEN} %1", 
"args1":[{"type":"input_statement", "name":"DO0"}], "previousStatement":null, "nextStatement":null, "style":"logic_blocks", "helpUrl":"%{BKY_CONTROLS_IF_HELPURL}", "mutator":"controls_if_mutator", "extensions":["controls_if_tooltip"]}, {"type":"controls_ifelse", "message0":"%{BKY_CONTROLS_IF_MSG_IF} %1", "args0":[{"type":"input_value", "name":"IF0", "check":"Boolean"}], "message1":"%{BKY_CONTROLS_IF_MSG_THEN} %1", "args1":[{"type":"input_statement", "name":"DO0"}], "message2":"%{BKY_CONTROLS_IF_MSG_ELSE} %1", 
"args2":[{"type":"input_statement", "name":"ELSE"}], "previousStatement":null, "nextStatement":null, "style":"logic_blocks", "tooltip":"%{BKYCONTROLS_IF_TOOLTIP_2}", "helpUrl":"%{BKY_CONTROLS_IF_HELPURL}", "extensions":["controls_if_tooltip"]}, {"type":"logic_compare", "message0":"%1 %2 %3", "args0":[{"type":"input_value", "name":"A"}, {"type":"field_dropdown", "name":"OP", "options":[["=", "EQ"], ["\u2260", "NEQ"], ["\u200f<", "LT"], ["\u200f\u2264", "LTE"], ["\u200f>", "GT"], ["\u200f\u2265", "GTE"]]}, 
{"type":"input_value", "name":"B"}], "inputsInline":true, "output":"Boolean", "style":"logic_blocks", "helpUrl":"%{BKY_LOGIC_COMPARE_HELPURL}", "extensions":["logic_compare", "logic_op_tooltip"]}, {"type":"logic_operation", "message0":"%1 %2 %3", "args0":[{"type":"input_value", "name":"A", "check":"Boolean"}, {"type":"field_dropdown", "name":"OP", "options":[["%{BKY_LOGIC_OPERATION_AND}", "AND"], ["%{BKY_LOGIC_OPERATION_OR}", "OR"]]}, {"type":"input_value", "name":"B", "check":"Boolean"}], "inputsInline":true, 
"output":"Boolean", "style":"logic_blocks", "helpUrl":"%{BKY_LOGIC_OPERATION_HELPURL}", "extensions":["logic_op_tooltip"]}, {"type":"logic_negate", "message0":"%{BKY_LOGIC_NEGATE_TITLE}", "args0":[{"type":"input_value", "name":"BOOL", "check":"Boolean"}], "output":"Boolean", "style":"logic_blocks", "tooltip":"%{BKY_LOGIC_NEGATE_TOOLTIP}", "helpUrl":"%{BKY_LOGIC_NEGATE_HELPURL}"}, {"type":"logic_null", "message0":"%{BKY_LOGIC_NULL}", "output":null, "style":"logic_blocks", "tooltip":"%{BKY_LOGIC_NULL_TOOLTIP}", 
"helpUrl":"%{BKY_LOGIC_NULL_HELPURL}"}, {"type":"logic_ternary", "message0":"%{BKY_LOGIC_TERNARY_CONDITION} %1", "args0":[{"type":"input_value", "name":"IF", "check":"Boolean"}], "message1":"%{BKY_LOGIC_TERNARY_IF_TRUE} %1", "args1":[{"type":"input_value", "name":"THEN"}], "message2":"%{BKY_LOGIC_TERNARY_IF_FALSE} %1", "args2":[{"type":"input_value", "name":"ELSE"}], "output":null, "style":"logic_blocks", "tooltip":"%{BKY_LOGIC_TERNARY_TOOLTIP}", "helpUrl":"%{BKY_LOGIC_TERNARY_HELPURL}", "extensions":["logic_ternary"]}]);
Blockly.defineBlocksWithJsonArray([{"type":"controls_if_if", "message0":"%{BKY_CONTROLS_IF_IF_TITLE_IF}", "nextStatement":null, "enableContextMenu":false, "style":"logic_blocks", "tooltip":"%{BKY_CONTROLS_IF_IF_TOOLTIP}"}, {"type":"controls_if_elseif", "message0":"%{BKY_CONTROLS_IF_ELSEIF_TITLE_ELSEIF}", "previousStatement":null, "nextStatement":null, "enableContextMenu":false, "style":"logic_blocks", "tooltip":"%{BKY_CONTROLS_IF_ELSEIF_TOOLTIP}"}, {"type":"controls_if_else", "message0":"%{BKY_CONTROLS_IF_ELSE_TITLE_ELSE}", 
"previousStatement":null, "enableContextMenu":false, "style":"logic_blocks", "tooltip":"%{BKY_CONTROLS_IF_ELSE_TOOLTIP}"}]);
Blockly.Constants.Logic.TOOLTIPS_BY_OP = {"EQ":"%{BKY_LOGIC_COMPARE_TOOLTIP_EQ}", "NEQ":"%{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}", "LT":"%{BKY_LOGIC_COMPARE_TOOLTIP_LT}", "LTE":"%{BKY_LOGIC_COMPARE_TOOLTIP_LTE}", "GT":"%{BKY_LOGIC_COMPARE_TOOLTIP_GT}", "GTE":"%{BKY_LOGIC_COMPARE_TOOLTIP_GTE}", "AND":"%{BKY_LOGIC_OPERATION_TOOLTIP_AND}", "OR":"%{BKY_LOGIC_OPERATION_TOOLTIP_OR}"};
Blockly.Extensions.register("logic_op_tooltip", Blockly.Extensions.buildTooltipForDropdown("OP", Blockly.Constants.Logic.TOOLTIPS_BY_OP));
Blockly.Constants.Logic.CONTROLS_IF_MUTATOR_MIXIN = {elseifCount_:0, elseCount_:0, mutationToDom:function() {
  if (!this.elseifCount_ && !this.elseCount_) {
    return null;
  }
  var container = document.createElement("mutation");
  if (this.elseifCount_) {
    container.setAttribute("elseif", this.elseifCount_);
  }
  if (this.elseCount_) {
    container.setAttribute("else", 1);
  }
  return container;
}, domToMutation:function(xmlElement) {
  this.elseifCount_ = parseInt(xmlElement.getAttribute("elseif"), 10) || 0;
  this.elseCount_ = parseInt(xmlElement.getAttribute("else"), 10) || 0;
  this.rebuildShape_();
}, decompose:function(workspace) {
  var containerBlock = workspace.newBlock("controls_if_if");
  containerBlock.initSvg();
  var connection = containerBlock.nextConnection;
  for (var i = 1; i <= this.elseifCount_; i++) {
    var elseifBlock = workspace.newBlock("controls_if_elseif");
    elseifBlock.initSvg();
    connection.connect(elseifBlock.previousConnection);
    connection = elseifBlock.nextConnection;
  }
  if (this.elseCount_) {
    var elseBlock = workspace.newBlock("controls_if_else");
    elseBlock.initSvg();
    connection.connect(elseBlock.previousConnection);
  }
  return containerBlock;
}, compose:function(containerBlock) {
  var clauseBlock = containerBlock.nextConnection.targetBlock();
  this.elseifCount_ = 0;
  this.elseCount_ = 0;
  var valueConnections = [null];
  var statementConnections = [null];
  var elseStatementConnection = null;
  while (clauseBlock) {
    switch(clauseBlock.type) {
      case "controls_if_elseif":
        this.elseifCount_++;
        valueConnections.push(clauseBlock.valueConnection_);
        statementConnections.push(clauseBlock.statementConnection_);
        break;
      case "controls_if_else":
        this.elseCount_++;
        elseStatementConnection = clauseBlock.statementConnection_;
        break;
      default:
        throw TypeError("Unknown block type: " + clauseBlock.type);
    }
    clauseBlock = clauseBlock.nextConnection && clauseBlock.nextConnection.targetBlock();
  }
  this.updateShape_();
  this.reconnectChildBlocks_(valueConnections, statementConnections, elseStatementConnection);
}, saveConnections:function(containerBlock) {
  var clauseBlock = containerBlock.nextConnection.targetBlock();
  var i = 1;
  while (clauseBlock) {
    switch(clauseBlock.type) {
      case "controls_if_elseif":
        var inputIf = this.getInput("IF" + i);
        var inputDo = this.getInput("DO" + i);
        clauseBlock.valueConnection_ = inputIf && inputIf.connection.targetConnection;
        clauseBlock.statementConnection_ = inputDo && inputDo.connection.targetConnection;
        i++;
        break;
      case "controls_if_else":
        var inputDo = this.getInput("ELSE");
        clauseBlock.statementConnection_ = inputDo && inputDo.connection.targetConnection;
        break;
      default:
        throw TypeError("Unknown block type: " + clauseBlock.type);
    }
    clauseBlock = clauseBlock.nextConnection && clauseBlock.nextConnection.targetBlock();
  }
}, rebuildShape_:function() {
  var valueConnections = [null];
  var statementConnections = [null];
  var elseStatementConnection = null;
  if (this.getInput("ELSE")) {
    elseStatementConnection = this.getInput("ELSE").connection.targetConnection;
  }
  var i = 1;
  while (this.getInput("IF" + i)) {
    var inputIf = this.getInput("IF" + i);
    var inputDo = this.getInput("DO" + i);
    valueConnections.push(inputIf.connection.targetConnection);
    statementConnections.push(inputDo.connection.targetConnection);
    i++;
  }
  this.updateShape_();
  this.reconnectChildBlocks_(valueConnections, statementConnections, elseStatementConnection);
}, updateShape_:function() {
  if (this.getInput("ELSE")) {
    this.removeInput("ELSE");
  }
  var i = 1;
  while (this.getInput("IF" + i)) {
    this.removeInput("IF" + i);
    this.removeInput("DO" + i);
    i++;
  }
  for (var i = 1; i <= this.elseifCount_; i++) {
    this.appendValueInput("IF" + i).setCheck("Boolean").appendField(Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"]);
    this.appendStatementInput("DO" + i).appendField(Blockly.Msg["CONTROLS_IF_MSG_THEN"]);
  }
  if (this.elseCount_) {
    this.appendStatementInput("ELSE").appendField(Blockly.Msg["CONTROLS_IF_MSG_ELSE"]);
  }
}, reconnectChildBlocks_:function(valueConnections, statementConnections, elseStatementConnection) {
  for (var i = 1; i <= this.elseifCount_; i++) {
    Blockly.Mutator.reconnect(valueConnections[i], this, "IF" + i);
    Blockly.Mutator.reconnect(statementConnections[i], this, "DO" + i);
  }
  Blockly.Mutator.reconnect(elseStatementConnection, this, "ELSE");
}};
Blockly.Extensions.registerMutator("controls_if_mutator", Blockly.Constants.Logic.CONTROLS_IF_MUTATOR_MIXIN, null, ["controls_if_elseif", "controls_if_else"]);
Blockly.Constants.Logic.CONTROLS_IF_TOOLTIP_EXTENSION = function() {
  this.setTooltip(function() {
    if (!this.elseifCount_ && !this.elseCount_) {
      return Blockly.Msg["CONTROLS_IF_TOOLTIP_1"];
    } else {
      if (!this.elseifCount_ && this.elseCount_) {
        return Blockly.Msg["CONTROLS_IF_TOOLTIP_2"];
      } else {
        if (this.elseifCount_ && !this.elseCount_) {
          return Blockly.Msg["CONTROLS_IF_TOOLTIP_3"];
        } else {
          if (this.elseifCount_ && this.elseCount_) {
            return Blockly.Msg["CONTROLS_IF_TOOLTIP_4"];
          }
        }
      }
    }
    return "";
  }.bind(this));
};
Blockly.Extensions.register("controls_if_tooltip", Blockly.Constants.Logic.CONTROLS_IF_TOOLTIP_EXTENSION);
Blockly.Constants.Logic.LOGIC_COMPARE_ONCHANGE_MIXIN = {onchange:function(e) {
  if (!this.prevBlocks_) {
    this.prevBlocks_ = [null, null];
  }
  var blockA = this.getInputTargetBlock("A");
  var blockB = this.getInputTargetBlock("B");
  if (blockA && blockB && !blockA.outputConnection.checkType_(blockB.outputConnection)) {
    Blockly.Events.setGroup(e.group);
    var prevA = this.prevBlocks_[0];
    if (prevA !== blockA) {
      blockA.unplug();
      if (prevA && !prevA.isShadow()) {
        this.getInput("A").connection.connect(prevA.outputConnection);
      }
    }
    var prevB = this.prevBlocks_[1];
    if (prevB !== blockB) {
      blockB.unplug();
      if (prevB && !prevB.isShadow()) {
        this.getInput("B").connection.connect(prevB.outputConnection);
      }
    }
    this.bumpNeighbours_();
    Blockly.Events.setGroup(false);
  }
  this.prevBlocks_[0] = this.getInputTargetBlock("A");
  this.prevBlocks_[1] = this.getInputTargetBlock("B");
}};
Blockly.Constants.Logic.LOGIC_COMPARE_EXTENSION = function() {
  this.mixin(Blockly.Constants.Logic.LOGIC_COMPARE_ONCHANGE_MIXIN);
};
Blockly.Extensions.register("logic_compare", Blockly.Constants.Logic.LOGIC_COMPARE_EXTENSION);
Blockly.Constants.Logic.LOGIC_TERNARY_ONCHANGE_MIXIN = {prevParentConnection_:null, onchange:function(e) {
  var blockA = this.getInputTargetBlock("THEN");
  var blockB = this.getInputTargetBlock("ELSE");
  var parentConnection = this.outputConnection.targetConnection;
  if ((blockA || blockB) && parentConnection) {
    for (var i = 0; i < 2; i++) {
      var block = i == 1 ? blockA : blockB;
      if (block && !block.outputConnection.checkType_(parentConnection)) {
        Blockly.Events.setGroup(e.group);
        if (parentConnection === this.prevParentConnection_) {
          this.unplug();
          parentConnection.getSourceBlock().bumpNeighbours_();
        } else {
          block.unplug();
          block.bumpNeighbours_();
        }
        Blockly.Events.setGroup(false);
      }
    }
  }
  this.prevParentConnection_ = parentConnection;
}};
Blockly.Extensions.registerMixin("logic_ternary", Blockly.Constants.Logic.LOGIC_TERNARY_ONCHANGE_MIXIN);
goog.provide("Blockly.Blocks.loops");
goog.provide("Blockly.Constants.Loops");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.Loops.HUE = 120;
Blockly.defineBlocksWithJsonArray([{"type":"controls_repeat_ext", "message0":"%{BKY_CONTROLS_REPEAT_TITLE}", "args0":[{"type":"input_value", "name":"TIMES", "check":"Number"}], "message1":"%{BKY_CONTROLS_REPEAT_INPUT_DO} %1", "args1":[{"type":"input_statement", "name":"DO"}], "previousStatement":null, "nextStatement":null, "style":"loop_blocks", "tooltip":"%{BKY_CONTROLS_REPEAT_TOOLTIP}", "helpUrl":"%{BKY_CONTROLS_REPEAT_HELPURL}"}, {"type":"controls_repeat", "message0":"%{BKY_CONTROLS_REPEAT_TITLE}", 
"args0":[{"type":"field_number", "name":"TIMES", "value":10, "min":0, "precision":1}], "message1":"%{BKY_CONTROLS_REPEAT_INPUT_DO} %1", "args1":[{"type":"input_statement", "name":"DO"}], "previousStatement":null, "nextStatement":null, "style":"loop_blocks", "tooltip":"%{BKY_CONTROLS_REPEAT_TOOLTIP}", "helpUrl":"%{BKY_CONTROLS_REPEAT_HELPURL}"}, {"type":"controls_whileUntil", "message0":"%1 %2", "args0":[{"type":"field_dropdown", "name":"MODE", "options":[["%{BKY_CONTROLS_WHILEUNTIL_OPERATOR_WHILE}", 
"WHILE"], ["%{BKY_CONTROLS_WHILEUNTIL_OPERATOR_UNTIL}", "UNTIL"]]}, {"type":"input_value", "name":"BOOL", "check":"Boolean"}], "message1":"%{BKY_CONTROLS_REPEAT_INPUT_DO} %1", "args1":[{"type":"input_statement", "name":"DO"}], "previousStatement":null, "nextStatement":null, "style":"loop_blocks", "helpUrl":"%{BKY_CONTROLS_WHILEUNTIL_HELPURL}", "extensions":["controls_whileUntil_tooltip"]}, {"type":"controls_for", "message0":"%{BKY_CONTROLS_FOR_TITLE}", "args0":[{"type":"field_variable", "name":"VAR", 
"variable":null}, {"type":"input_value", "name":"FROM", "check":"Number", "align":"RIGHT"}, {"type":"input_value", "name":"TO", "check":"Number", "align":"RIGHT"}, {"type":"input_value", "name":"BY", "check":"Number", "align":"RIGHT"}], "message1":"%{BKY_CONTROLS_REPEAT_INPUT_DO} %1", "args1":[{"type":"input_statement", "name":"DO"}], "inputsInline":true, "previousStatement":null, "nextStatement":null, "style":"loop_blocks", "helpUrl":"%{BKY_CONTROLS_FOR_HELPURL}", "extensions":["contextMenu_newGetVariableBlock", 
"controls_for_tooltip"]}, {"type":"controls_forEach", "message0":"%{BKY_CONTROLS_FOREACH_TITLE}", "args0":[{"type":"field_variable", "name":"VAR", "variable":null}, {"type":"input_value", "name":"LIST", "check":"Array"}], "message1":"%{BKY_CONTROLS_REPEAT_INPUT_DO} %1", "args1":[{"type":"input_statement", "name":"DO"}], "previousStatement":null, "nextStatement":null, "style":"loop_blocks", "helpUrl":"%{BKY_CONTROLS_FOREACH_HELPURL}", "extensions":["contextMenu_newGetVariableBlock", "controls_forEach_tooltip"]}, 
{"type":"controls_flow_statements", "message0":"%1", "args0":[{"type":"field_dropdown", "name":"FLOW", "options":[["%{BKY_CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK}", "BREAK"], ["%{BKY_CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE}", "CONTINUE"]]}], "previousStatement":null, "style":"loop_blocks", "helpUrl":"%{BKY_CONTROLS_FLOW_STATEMENTS_HELPURL}", "extensions":["controls_flow_tooltip", "controls_flow_in_loop_check"]}]);
Blockly.Constants.Loops.WHILE_UNTIL_TOOLTIPS = {"WHILE":"%{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}", "UNTIL":"%{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}"};
Blockly.Extensions.register("controls_whileUntil_tooltip", Blockly.Extensions.buildTooltipForDropdown("MODE", Blockly.Constants.Loops.WHILE_UNTIL_TOOLTIPS));
Blockly.Constants.Loops.BREAK_CONTINUE_TOOLTIPS = {"BREAK":"%{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}", "CONTINUE":"%{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}"};
Blockly.Extensions.register("controls_flow_tooltip", Blockly.Extensions.buildTooltipForDropdown("FLOW", Blockly.Constants.Loops.BREAK_CONTINUE_TOOLTIPS));
Blockly.Constants.Loops.CUSTOM_CONTEXT_MENU_CREATE_VARIABLES_GET_MIXIN = {customContextMenu:function(options) {
  if (this.isInFlyout) {
    return;
  }
  var variable = this.getField("VAR").getVariable();
  var varName = variable.name;
  if (!this.isCollapsed() && varName != null) {
    var option = {enabled:true};
    option.text = Blockly.Msg["VARIABLES_SET_CREATE_GET"].replace("%1", varName);
    var xmlField = Blockly.Variables.generateVariableFieldDom(variable);
    var xmlBlock = document.createElement("block");
    xmlBlock.setAttribute("type", "variables_get");
    xmlBlock.appendChild(xmlField);
    option.callback = Blockly.ContextMenu.callbackFactory(this, xmlBlock);
    options.push(option);
  }
}};
Blockly.Extensions.registerMixin("contextMenu_newGetVariableBlock", Blockly.Constants.Loops.CUSTOM_CONTEXT_MENU_CREATE_VARIABLES_GET_MIXIN);
Blockly.Extensions.register("controls_for_tooltip", Blockly.Extensions.buildTooltipWithFieldText("%{BKY_CONTROLS_FOR_TOOLTIP}", "VAR"));
Blockly.Extensions.register("controls_forEach_tooltip", Blockly.Extensions.buildTooltipWithFieldText("%{BKY_CONTROLS_FOREACH_TOOLTIP}", "VAR"));
Blockly.Constants.Loops.CONTROL_FLOW_IN_LOOP_CHECK_MIXIN = {LOOP_TYPES:["controls_repeat", "controls_repeat_ext", "controls_forEach", "controls_for", "controls_whileUntil"], onchange:function() {
  if (!this.workspace.isDragging || this.workspace.isDragging()) {
    return;
  }
  var legal = false;
  var block = this;
  do {
    if (this.LOOP_TYPES.indexOf(block.type) != -1) {
      legal = true;
      break;
    }
    block = block.getSurroundParent();
  } while (block);
  if (legal) {
    this.setWarningText(null);
    if (!this.isInFlyout) {
      this.setDisabled(false);
    }
  } else {
    this.setWarningText(Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"]);
    if (!this.isInFlyout && !this.getInheritedDisabled()) {
      this.setDisabled(true);
    }
  }
}};
Blockly.Extensions.registerMixin("controls_flow_in_loop_check", Blockly.Constants.Loops.CONTROL_FLOW_IN_LOOP_CHECK_MIXIN);
goog.provide("Blockly.Blocks.math");
goog.provide("Blockly.Constants.Math");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.Math.HUE = 230;
Blockly.defineBlocksWithJsonArray([{"type":"math_number", "message0":"%1", "args0":[{"type":"field_number", "name":"NUM", "value":0}], "output":"Number", "helpUrl":"%{BKY_MATH_NUMBER_HELPURL}", "style":"math_blocks", "tooltip":"%{BKY_MATH_NUMBER_TOOLTIP}", "extensions":["parent_tooltip_when_inline"]}, {"type":"math_arithmetic", "message0":"%1 %2 %3", "args0":[{"type":"input_value", "name":"A", "check":"Number"}, {"type":"field_dropdown", "name":"OP", "options":[["%{BKY_MATH_ADDITION_SYMBOL}", "ADD"], 
["%{BKY_MATH_SUBTRACTION_SYMBOL}", "MINUS"], ["%{BKY_MATH_MULTIPLICATION_SYMBOL}", "MULTIPLY"], ["%{BKY_MATH_DIVISION_SYMBOL}", "DIVIDE"], ["%{BKY_MATH_POWER_SYMBOL}", "POWER"]]}, {"type":"input_value", "name":"B", "check":"Number"}], "inputsInline":true, "output":"Number", "style":"math_blocks", "helpUrl":"%{BKY_MATH_ARITHMETIC_HELPURL}", "extensions":["math_op_tooltip"]}, {"type":"math_single", "message0":"%1 %2", "args0":[{"type":"field_dropdown", "name":"OP", "options":[["%{BKY_MATH_SINGLE_OP_ROOT}", 
"ROOT"], ["%{BKY_MATH_SINGLE_OP_ABSOLUTE}", "ABS"], ["-", "NEG"], ["ln", "LN"], ["log10", "LOG10"], ["e^", "EXP"], ["10^", "POW10"]]}, {"type":"input_value", "name":"NUM", "check":"Number"}], "output":"Number", "style":"math_blocks", "helpUrl":"%{BKY_MATH_SINGLE_HELPURL}", "extensions":["math_op_tooltip"]}, {"type":"math_trig", "message0":"%1 %2", "args0":[{"type":"field_dropdown", "name":"OP", "options":[["%{BKY_MATH_TRIG_SIN}", "SIN"], ["%{BKY_MATH_TRIG_COS}", "COS"], ["%{BKY_MATH_TRIG_TAN}", "TAN"], 
["%{BKY_MATH_TRIG_ASIN}", "ASIN"], ["%{BKY_MATH_TRIG_ACOS}", "ACOS"], ["%{BKY_MATH_TRIG_ATAN}", "ATAN"]]}, {"type":"input_value", "name":"NUM", "check":"Number"}], "output":"Number", "style":"math_blocks", "helpUrl":"%{BKY_MATH_TRIG_HELPURL}", "extensions":["math_op_tooltip"]}, {"type":"math_constant", "message0":"%1", "args0":[{"type":"field_dropdown", "name":"CONSTANT", "options":[["\u03c0", "PI"], ["e", "E"], ["\u03c6", "GOLDEN_RATIO"], ["sqrt(2)", "SQRT2"], ["sqrt(\u00bd)", "SQRT1_2"], ["\u221e", 
"INFINITY"]]}], "output":"Number", "style":"math_blocks", "tooltip":"%{BKY_MATH_CONSTANT_TOOLTIP}", "helpUrl":"%{BKY_MATH_CONSTANT_HELPURL}"}, {"type":"math_number_property", "message0":"%1 %2", "args0":[{"type":"input_value", "name":"NUMBER_TO_CHECK", "check":"Number"}, {"type":"field_dropdown", "name":"PROPERTY", "options":[["%{BKY_MATH_IS_EVEN}", "EVEN"], ["%{BKY_MATH_IS_ODD}", "ODD"], ["%{BKY_MATH_IS_PRIME}", "PRIME"], ["%{BKY_MATH_IS_WHOLE}", "WHOLE"], ["%{BKY_MATH_IS_POSITIVE}", "POSITIVE"], 
["%{BKY_MATH_IS_NEGATIVE}", "NEGATIVE"], ["%{BKY_MATH_IS_DIVISIBLE_BY}", "DIVISIBLE_BY"]]}], "inputsInline":true, "output":"Boolean", "style":"math_blocks", "tooltip":"%{BKY_MATH_IS_TOOLTIP}", "mutator":"math_is_divisibleby_mutator"}, {"type":"math_change", "message0":"%{BKY_MATH_CHANGE_TITLE}", "args0":[{"type":"field_variable", "name":"VAR", "variable":"%{BKY_MATH_CHANGE_TITLE_ITEM}"}, {"type":"input_value", "name":"DELTA", "check":"Number"}], "previousStatement":null, "nextStatement":null, "style":"variable_blocks", 
"helpUrl":"%{BKY_MATH_CHANGE_HELPURL}", "extensions":["math_change_tooltip"]}, {"type":"math_round", "message0":"%1 %2", "args0":[{"type":"field_dropdown", "name":"OP", "options":[["%{BKY_MATH_ROUND_OPERATOR_ROUND}", "ROUND"], ["%{BKY_MATH_ROUND_OPERATOR_ROUNDUP}", "ROUNDUP"], ["%{BKY_MATH_ROUND_OPERATOR_ROUNDDOWN}", "ROUNDDOWN"]]}, {"type":"input_value", "name":"NUM", "check":"Number"}], "output":"Number", "style":"math_blocks", "helpUrl":"%{BKY_MATH_ROUND_HELPURL}", "tooltip":"%{BKY_MATH_ROUND_TOOLTIP}"}, 
{"type":"math_on_list", "message0":"%1 %2", "args0":[{"type":"field_dropdown", "name":"OP", "options":[["%{BKY_MATH_ONLIST_OPERATOR_SUM}", "SUM"], ["%{BKY_MATH_ONLIST_OPERATOR_MIN}", "MIN"], ["%{BKY_MATH_ONLIST_OPERATOR_MAX}", "MAX"], ["%{BKY_MATH_ONLIST_OPERATOR_AVERAGE}", "AVERAGE"], ["%{BKY_MATH_ONLIST_OPERATOR_MEDIAN}", "MEDIAN"], ["%{BKY_MATH_ONLIST_OPERATOR_MODE}", "MODE"], ["%{BKY_MATH_ONLIST_OPERATOR_STD_DEV}", "STD_DEV"], ["%{BKY_MATH_ONLIST_OPERATOR_RANDOM}", "RANDOM"]]}, {"type":"input_value", 
"name":"LIST", "check":"Array"}], "output":"Number", "style":"math_blocks", "helpUrl":"%{BKY_MATH_ONLIST_HELPURL}", "mutator":"math_modes_of_list_mutator", "extensions":["math_op_tooltip"]}, {"type":"math_modulo", "message0":"%{BKY_MATH_MODULO_TITLE}", "args0":[{"type":"input_value", "name":"DIVIDEND", "check":"Number"}, {"type":"input_value", "name":"DIVISOR", "check":"Number"}], "inputsInline":true, "output":"Number", "style":"math_blocks", "tooltip":"%{BKY_MATH_MODULO_TOOLTIP}", "helpUrl":"%{BKY_MATH_MODULO_HELPURL}"}, 
{"type":"math_constrain", "message0":"%{BKY_MATH_CONSTRAIN_TITLE}", "args0":[{"type":"input_value", "name":"VALUE", "check":"Number"}, {"type":"input_value", "name":"LOW", "check":"Number"}, {"type":"input_value", "name":"HIGH", "check":"Number"}], "inputsInline":true, "output":"Number", "style":"math_blocks", "tooltip":"%{BKY_MATH_CONSTRAIN_TOOLTIP}", "helpUrl":"%{BKY_MATH_CONSTRAIN_HELPURL}"}, {"type":"math_random_int", "message0":"%{BKY_MATH_RANDOM_INT_TITLE}", "args0":[{"type":"input_value", 
"name":"FROM", "check":"Number"}, {"type":"input_value", "name":"TO", "check":"Number"}], "inputsInline":true, "output":"Number", "style":"math_blocks", "tooltip":"%{BKY_MATH_RANDOM_INT_TOOLTIP}", "helpUrl":"%{BKY_MATH_RANDOM_INT_HELPURL}"}, {"type":"math_random_float", "message0":"%{BKY_MATH_RANDOM_FLOAT_TITLE_RANDOM}", "output":"Number", "style":"math_blocks", "tooltip":"%{BKY_MATH_RANDOM_FLOAT_TOOLTIP}", "helpUrl":"%{BKY_MATH_RANDOM_FLOAT_HELPURL}"}, {"type":"math_atan2", "message0":"%{BKY_MATH_ATAN2_TITLE}", 
"args0":[{"type":"input_value", "name":"X", "check":"Number"}, {"type":"input_value", "name":"Y", "check":"Number"}], "inputsInline":true, "output":"Number", "style":"math_blocks", "tooltip":"%{BKY_MATH_ATAN2_TOOLTIP}", "helpUrl":"%{BKY_MATH_ATAN2_HELPURL}"}]);
Blockly.Constants.Math.TOOLTIPS_BY_OP = {"ADD":"%{BKY_MATH_ARITHMETIC_TOOLTIP_ADD}", "MINUS":"%{BKY_MATH_ARITHMETIC_TOOLTIP_MINUS}", "MULTIPLY":"%{BKY_MATH_ARITHMETIC_TOOLTIP_MULTIPLY}", "DIVIDE":"%{BKY_MATH_ARITHMETIC_TOOLTIP_DIVIDE}", "POWER":"%{BKY_MATH_ARITHMETIC_TOOLTIP_POWER}", "ROOT":"%{BKY_MATH_SINGLE_TOOLTIP_ROOT}", "ABS":"%{BKY_MATH_SINGLE_TOOLTIP_ABS}", "NEG":"%{BKY_MATH_SINGLE_TOOLTIP_NEG}", "LN":"%{BKY_MATH_SINGLE_TOOLTIP_LN}", "LOG10":"%{BKY_MATH_SINGLE_TOOLTIP_LOG10}", "EXP":"%{BKY_MATH_SINGLE_TOOLTIP_EXP}", 
"POW10":"%{BKY_MATH_SINGLE_TOOLTIP_POW10}", "SIN":"%{BKY_MATH_TRIG_TOOLTIP_SIN}", "COS":"%{BKY_MATH_TRIG_TOOLTIP_COS}", "TAN":"%{BKY_MATH_TRIG_TOOLTIP_TAN}", "ASIN":"%{BKY_MATH_TRIG_TOOLTIP_ASIN}", "ACOS":"%{BKY_MATH_TRIG_TOOLTIP_ACOS}", "ATAN":"%{BKY_MATH_TRIG_TOOLTIP_ATAN}", "SUM":"%{BKY_MATH_ONLIST_TOOLTIP_SUM}", "MIN":"%{BKY_MATH_ONLIST_TOOLTIP_MIN}", "MAX":"%{BKY_MATH_ONLIST_TOOLTIP_MAX}", "AVERAGE":"%{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}", "MEDIAN":"%{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}", "MODE":"%{BKY_MATH_ONLIST_TOOLTIP_MODE}", 
"STD_DEV":"%{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}", "RANDOM":"%{BKY_MATH_ONLIST_TOOLTIP_RANDOM}"};
Blockly.Extensions.register("math_op_tooltip", Blockly.Extensions.buildTooltipForDropdown("OP", Blockly.Constants.Math.TOOLTIPS_BY_OP));
Blockly.Constants.Math.IS_DIVISIBLEBY_MUTATOR_MIXIN = {mutationToDom:function() {
  var container = document.createElement("mutation");
  var divisorInput = this.getFieldValue("PROPERTY") == "DIVISIBLE_BY";
  container.setAttribute("divisor_input", divisorInput);
  return container;
}, domToMutation:function(xmlElement) {
  var divisorInput = xmlElement.getAttribute("divisor_input") == "true";
  this.updateShape_(divisorInput);
}, updateShape_:function(divisorInput) {
  var inputExists = this.getInput("DIVISOR");
  if (divisorInput) {
    if (!inputExists) {
      this.appendValueInput("DIVISOR").setCheck("Number");
    }
  } else {
    if (inputExists) {
      this.removeInput("DIVISOR");
    }
  }
}};
Blockly.Constants.Math.IS_DIVISIBLE_MUTATOR_EXTENSION = function() {
  this.getField("PROPERTY").setValidator(function(option) {
    var divisorInput = option == "DIVISIBLE_BY";
    this.sourceBlock_.updateShape_(divisorInput);
  });
};
Blockly.Extensions.registerMutator("math_is_divisibleby_mutator", Blockly.Constants.Math.IS_DIVISIBLEBY_MUTATOR_MIXIN, Blockly.Constants.Math.IS_DIVISIBLE_MUTATOR_EXTENSION);
Blockly.Extensions.register("math_change_tooltip", Blockly.Extensions.buildTooltipWithFieldText("%{BKY_MATH_CHANGE_TOOLTIP}", "VAR"));
Blockly.Constants.Math.LIST_MODES_MUTATOR_MIXIN = {updateType_:function(newOp) {
  if (newOp == "MODE") {
    this.outputConnection.setCheck("Array");
  } else {
    this.outputConnection.setCheck("Number");
  }
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("op", this.getFieldValue("OP"));
  return container;
}, domToMutation:function(xmlElement) {
  this.updateType_(xmlElement.getAttribute("op"));
}};
Blockly.Constants.Math.LIST_MODES_MUTATOR_EXTENSION = function() {
  this.getField("OP").setValidator(function(newOp) {
    this.updateType_(newOp);
  }.bind(this));
};
Blockly.Extensions.registerMutator("math_modes_of_list_mutator", Blockly.Constants.Math.LIST_MODES_MUTATOR_MIXIN, Blockly.Constants.Math.LIST_MODES_MUTATOR_EXTENSION);
goog.provide("Blockly.Blocks.procedures");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Blocks["procedures_defnoreturn"] = {init:function() {
  var nameField = new Blockly.FieldTextInput("", Blockly.Procedures.rename);
  nameField.setSpellcheck(false);
  this.appendDummyInput().appendField(Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"]).appendField(nameField, "NAME").appendField("", "PARAMS");
  this.setMutator(new Blockly.Mutator(["procedures_mutatorarg"]));
  if ((this.workspace.options.comments || this.workspace.options.parentWorkspace && this.workspace.options.parentWorkspace.options.comments) && Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"]) {
    this.setCommentText(Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"]);
  }
  this.setStyle("procedure_blocks");
  this.setTooltip(Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"]);
  this.setHelpUrl(Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"]);
  this.arguments_ = [];
  this.argumentVarModels_ = [];
  this.setStatements_(true);
  this.statementConnection_ = null;
}, setStatements_:function(hasStatements) {
  if (this.hasStatements_ === hasStatements) {
    return;
  }
  if (hasStatements) {
    this.appendStatementInput("STACK").appendField(Blockly.Msg["PROCEDURES_DEFNORETURN_DO"]);
    if (this.getInput("RETURN")) {
      this.moveInputBefore("STACK", "RETURN");
    }
  } else {
    this.removeInput("STACK", true);
  }
  this.hasStatements_ = hasStatements;
}, updateParams_:function() {
  var paramString = "";
  if (this.arguments_.length) {
    paramString = Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] + " " + this.arguments_.join(", ");
  }
  Blockly.Events.disable();
  try {
    this.setFieldValue(paramString, "PARAMS");
  } finally {
    Blockly.Events.enable();
  }
}, mutationToDom:function(opt_paramIds) {
  var container = document.createElement("mutation");
  if (opt_paramIds) {
    container.setAttribute("name", this.getFieldValue("NAME"));
  }
  for (var i = 0; i < this.argumentVarModels_.length; i++) {
    var parameter = document.createElement("arg");
    var argModel = this.argumentVarModels_[i];
    parameter.setAttribute("name", argModel.name);
    parameter.setAttribute("varid", argModel.getId());
    if (opt_paramIds && this.paramIds_) {
      parameter.setAttribute("paramId", this.paramIds_[i]);
    }
    container.appendChild(parameter);
  }
  if (!this.hasStatements_) {
    container.setAttribute("statements", "false");
  }
  return container;
}, domToMutation:function(xmlElement) {
  this.arguments_ = [];
  this.argumentVarModels_ = [];
  for (var i = 0, childNode; childNode = xmlElement.childNodes[i]; i++) {
    if (childNode.nodeName.toLowerCase() == "arg") {
      var varName = childNode.getAttribute("name");
      var varId = childNode.getAttribute("varid") || childNode.getAttribute("varId");
      this.arguments_.push(varName);
      var variable = Blockly.Variables.getOrCreateVariablePackage(this.workspace, varId, varName, "");
      if (variable != null) {
        this.argumentVarModels_.push(variable);
      } else {
        console.log("Failed to create a variable with name " + varName + ", ignoring.");
      }
    }
  }
  this.updateParams_();
  Blockly.Procedures.mutateCallers(this);
  this.setStatements_(xmlElement.getAttribute("statements") !== "false");
}, decompose:function(workspace) {
  var containerBlock = workspace.newBlock("procedures_mutatorcontainer");
  containerBlock.initSvg();
  if (this.getInput("RETURN")) {
    containerBlock.setFieldValue(this.hasStatements_ ? "TRUE" : "FALSE", "STATEMENTS");
  } else {
    containerBlock.getInput("STATEMENT_INPUT").setVisible(false);
  }
  var connection = containerBlock.getInput("STACK").connection;
  for (var i = 0; i < this.arguments_.length; i++) {
    var paramBlock = workspace.newBlock("procedures_mutatorarg");
    paramBlock.initSvg();
    paramBlock.setFieldValue(this.arguments_[i], "NAME");
    paramBlock.oldLocation = i;
    connection.connect(paramBlock.previousConnection);
    connection = paramBlock.nextConnection;
  }
  Blockly.Procedures.mutateCallers(this);
  return containerBlock;
}, compose:function(containerBlock) {
  this.arguments_ = [];
  this.paramIds_ = [];
  this.argumentVarModels_ = [];
  var paramBlock = containerBlock.getInputTargetBlock("STACK");
  while (paramBlock) {
    var varName = paramBlock.getFieldValue("NAME");
    this.arguments_.push(varName);
    var variable = this.workspace.getVariable(varName, "");
    if (variable != null) {
      this.argumentVarModels_.push(variable);
    } else {
      console.log("Failed to get variable named " + varName + ", ignoring.");
    }
    this.paramIds_.push(paramBlock.id);
    paramBlock = paramBlock.nextConnection && paramBlock.nextConnection.targetBlock();
  }
  this.updateParams_();
  Blockly.Procedures.mutateCallers(this);
  var hasStatements = containerBlock.getFieldValue("STATEMENTS");
  if (hasStatements !== null) {
    hasStatements = hasStatements == "TRUE";
    if (this.hasStatements_ != hasStatements) {
      if (hasStatements) {
        this.setStatements_(true);
        Blockly.Mutator.reconnect(this.statementConnection_, this, "STACK");
        this.statementConnection_ = null;
      } else {
        var stackConnection = this.getInput("STACK").connection;
        this.statementConnection_ = stackConnection.targetConnection;
        if (this.statementConnection_) {
          var stackBlock = stackConnection.targetBlock();
          stackBlock.unplug();
          stackBlock.bumpNeighbours_();
        }
        this.setStatements_(false);
      }
    }
  }
}, getProcedureDef:function() {
  return [this.getFieldValue("NAME"), this.arguments_, false];
}, getVars:function() {
  return this.arguments_;
}, getVarModels:function() {
  return this.argumentVarModels_;
}, renameVarById:function(oldId, newId) {
  var oldVariable = this.workspace.getVariableById(oldId);
  if (oldVariable.type != "") {
    return;
  }
  var oldName = oldVariable.name;
  var newVar = this.workspace.getVariableById(newId);
  var change = false;
  for (var i = 0; i < this.argumentVarModels_.length; i++) {
    if (this.argumentVarModels_[i].getId() == oldId) {
      this.arguments_[i] = newVar.name;
      this.argumentVarModels_[i] = newVar;
      change = true;
    }
  }
  if (change) {
    this.displayRenamedVar_(oldName, newVar.name);
    Blockly.Procedures.mutateCallers(this);
  }
}, updateVarName:function(variable) {
  var newName = variable.name;
  var change = false;
  for (var i = 0; i < this.argumentVarModels_.length; i++) {
    if (this.argumentVarModels_[i].getId() == variable.getId()) {
      var oldName = this.arguments_[i];
      this.arguments_[i] = newName;
      change = true;
    }
  }
  if (change) {
    this.displayRenamedVar_(oldName, newName);
    Blockly.Procedures.mutateCallers(this);
  }
}, displayRenamedVar_:function(oldName, newName) {
  this.updateParams_();
  if (this.mutator.isVisible()) {
    var blocks = this.mutator.workspace_.getAllBlocks(false);
    for (var i = 0, block; block = blocks[i]; i++) {
      if (block.type == "procedures_mutatorarg" && Blockly.Names.equals(oldName, block.getFieldValue("NAME"))) {
        block.setFieldValue(newName, "NAME");
      }
    }
  }
}, customContextMenu:function(options) {
  if (this.isInFlyout) {
    return;
  }
  var option = {enabled:true};
  var name = this.getFieldValue("NAME");
  option.text = Blockly.Msg["PROCEDURES_CREATE_DO"].replace("%1", name);
  var xmlMutation = document.createElement("mutation");
  xmlMutation.setAttribute("name", name);
  for (var i = 0; i < this.arguments_.length; i++) {
    var xmlArg = document.createElement("arg");
    xmlArg.setAttribute("name", this.arguments_[i]);
    xmlMutation.appendChild(xmlArg);
  }
  var xmlBlock = document.createElement("block");
  xmlBlock.setAttribute("type", this.callType_);
  xmlBlock.appendChild(xmlMutation);
  option.callback = Blockly.ContextMenu.callbackFactory(this, xmlBlock);
  options.push(option);
  if (!this.isCollapsed()) {
    for (var i = 0; i < this.argumentVarModels_.length; i++) {
      var option = {enabled:true};
      var argVar = this.argumentVarModels_[i];
      var name = argVar.name;
      option.text = Blockly.Msg["VARIABLES_SET_CREATE_GET"].replace("%1", name);
      var xmlField = Blockly.Variables.generateVariableFieldDom(argVar);
      var xmlBlock = document.createElement("block");
      xmlBlock.setAttribute("type", "variables_get");
      xmlBlock.appendChild(xmlField);
      option.callback = Blockly.ContextMenu.callbackFactory(this, xmlBlock);
      options.push(option);
    }
  }
}, callType_:"procedures_callnoreturn"};
Blockly.Blocks["procedures_defreturn"] = {init:function() {
  var nameField = new Blockly.FieldTextInput("", Blockly.Procedures.rename);
  nameField.setSpellcheck(false);
  this.appendDummyInput().appendField(Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"]).appendField(nameField, "NAME").appendField("", "PARAMS");
  this.appendValueInput("RETURN").setAlign(Blockly.ALIGN_RIGHT).appendField(Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"]);
  this.setMutator(new Blockly.Mutator(["procedures_mutatorarg"]));
  if ((this.workspace.options.comments || this.workspace.options.parentWorkspace && this.workspace.options.parentWorkspace.options.comments) && Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"]) {
    this.setCommentText(Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"]);
  }
  this.setStyle("procedure_blocks");
  this.setTooltip(Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"]);
  this.setHelpUrl(Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"]);
  this.arguments_ = [];
  this.argumentVarModels_ = [];
  this.setStatements_(true);
  this.statementConnection_ = null;
}, setStatements_:Blockly.Blocks["procedures_defnoreturn"].setStatements_, updateParams_:Blockly.Blocks["procedures_defnoreturn"].updateParams_, mutationToDom:Blockly.Blocks["procedures_defnoreturn"].mutationToDom, domToMutation:Blockly.Blocks["procedures_defnoreturn"].domToMutation, decompose:Blockly.Blocks["procedures_defnoreturn"].decompose, compose:Blockly.Blocks["procedures_defnoreturn"].compose, getProcedureDef:function() {
  return [this.getFieldValue("NAME"), this.arguments_, true];
}, getVars:Blockly.Blocks["procedures_defnoreturn"].getVars, getVarModels:Blockly.Blocks["procedures_defnoreturn"].getVarModels, renameVarById:Blockly.Blocks["procedures_defnoreturn"].renameVarById, updateVarName:Blockly.Blocks["procedures_defnoreturn"].updateVarName, displayRenamedVar_:Blockly.Blocks["procedures_defnoreturn"].displayRenamedVar_, customContextMenu:Blockly.Blocks["procedures_defnoreturn"].customContextMenu, callType_:"procedures_callreturn"};
Blockly.Blocks["procedures_mutatorcontainer"] = {init:function() {
  this.appendDummyInput().appendField(Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"]);
  this.appendStatementInput("STACK");
  this.appendDummyInput("STATEMENT_INPUT").appendField(Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"]).appendField(new Blockly.FieldCheckbox("TRUE"), "STATEMENTS");
  this.setStyle("procedure_blocks");
  this.setTooltip(Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"]);
  this.contextMenu = false;
}, onchange:function(event) {
  if (!this.workspace || this.workspace.isFlyout || event.type != Blockly.Events.BLOCK_DELETE && event.type != Blockly.Events.BLOCK_CREATE) {
    return;
  }
  var blocks = this.workspace.getAllBlocks();
  var allVariables = this.workspace.getAllVariables();
  if (event.type == Blockly.Events.BLOCK_DELETE) {
    var variableNamesToKeep = [];
    for (var i = 0; i < blocks.length; i += 1) {
      if (blocks[i].getFieldValue("NAME")) {
        variableNamesToKeep.push(blocks[i].getFieldValue("NAME"));
      }
    }
    for (var k = 0; k < allVariables.length; k += 1) {
      if (variableNamesToKeep.indexOf(allVariables[k].name) == -1) {
        this.workspace.deleteVariableById(allVariables[k].getId());
      }
    }
    return;
  }
  if (event.type != Blockly.Events.BLOCK_CREATE) {
    return;
  }
  var block = this.workspace.getBlockById(event.blockId);
  if (!block.getField("NAME")) {
    return;
  }
  var varName = block.getFieldValue("NAME");
  var variable = this.workspace.getVariable(varName);
  if (!variable) {
    variable = this.workspace.createVariable(varName);
  }
  if (block.previousConnection.isConnected() || block.nextConnection.isConnected()) {
    return;
  }
  for (var j = 0; j < blocks.length; j += 1) {
    if (block.id != blocks[j].id && blocks[j].getFieldValue("NAME") == variable.name) {
      varName = Blockly.Variables.generateUniqueName(this.workspace);
      variable = this.workspace.createVariable(varName);
      block.setFieldValue(variable.name, "NAME");
      return;
    }
  }
}};
Blockly.Blocks["procedures_mutatorarg"] = {init:function() {
  var field = new Blockly.FieldTextInput("x", this.validator_);
  field.oldShowEditorFn_ = field.showEditor_;
  var newShowEditorFn = function() {
    this.createdVariables_ = [];
    this.oldShowEditorFn_();
  };
  field.showEditor_ = newShowEditorFn;
  this.appendDummyInput().appendField(Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"]).appendField(field, "NAME");
  this.setPreviousStatement(true);
  this.setNextStatement(true);
  this.setStyle("procedure_blocks");
  this.setTooltip(Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"]);
  this.contextMenu = false;
  field.onFinishEditing_ = this.deleteIntermediateVars_;
  field.createdVariables_ = [];
  field.onFinishEditing_("x");
}, validator_:function(varName) {
  var outerWs = Blockly.Mutator.findParentWs(this.sourceBlock_.workspace);
  varName = varName.replace(/[\s\xa0]+/g, " ").replace(/^ | $/g, "");
  if (!varName) {
    return null;
  }
  var blocks = this.sourceBlock_.workspace.getAllBlocks();
  for (var i = 0; i < blocks.length; i += 1) {
    if (blocks[i].id == this.sourceBlock_.id) {
      continue;
    }
    if (blocks[i].getFieldValue("NAME") == varName) {
      return null;
    }
  }
  var model = outerWs.getVariable(varName, "");
  if (model && model.name != varName) {
    outerWs.renameVarById(model.getId(), varName);
  }
  if (!model) {
    model = outerWs.createVariable(varName, "");
    if (model && this.createdVariables_) {
      this.createdVariables_.push(model);
    }
  }
  return varName;
}, deleteIntermediateVars_:function(newText) {
  var outerWs = Blockly.Mutator.findParentWs(this.sourceBlock_.workspace);
  if (!outerWs) {
    return;
  }
  for (var i = 0; i < this.createdVariables_.length; i++) {
    var model = this.createdVariables_[i];
    if (model.name != newText) {
      outerWs.deleteVariableById(model.getId());
    }
  }
}};
Blockly.Blocks["procedures_callnoreturn"] = {init:function() {
  this.appendDummyInput("TOPROW").appendField(this.id, "NAME");
  this.setPreviousStatement(true);
  this.setNextStatement(true);
  this.setStyle("procedure_blocks");
  this.setHelpUrl(Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"]);
  this.arguments_ = [];
  this.argumentVarModels_ = [];
  this.quarkConnections_ = {};
  this.quarkIds_ = null;
  this.previousDisabledState_ = false;
}, getProcedureCall:function() {
  return this.getFieldValue("NAME");
}, renameProcedure:function(oldName, newName) {
  if (Blockly.Names.equals(oldName, this.getProcedureCall())) {
    this.setFieldValue(newName, "NAME");
    var baseMsg = this.outputConnection ? Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] : Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"];
    this.setTooltip(baseMsg.replace("%1", newName));
  }
}, setProcedureParameters_:function(paramNames, paramIds) {
  var defBlock = Blockly.Procedures.getDefinition(this.getProcedureCall(), this.workspace);
  var mutatorOpen = defBlock && defBlock.mutator && defBlock.mutator.isVisible();
  if (!mutatorOpen) {
    this.quarkConnections_ = {};
    this.quarkIds_ = null;
  }
  if (!paramIds) {
    return;
  }
  if (paramNames.join("\n") == this.arguments_.join("\n")) {
    this.quarkIds_ = paramIds;
    return;
  }
  if (paramIds.length != paramNames.length) {
    throw RangeError("paramNames and paramIds must be the same length.");
  }
  this.setCollapsed(false);
  if (!this.quarkIds_) {
    this.quarkConnections_ = {};
    this.quarkIds_ = [];
  }
  var savedRendered = this.rendered;
  this.rendered = false;
  for (var i = 0; i < this.arguments_.length; i++) {
    var input = this.getInput("ARG" + i);
    if (input) {
      var connection = input.connection.targetConnection;
      this.quarkConnections_[this.quarkIds_[i]] = connection;
      if (mutatorOpen && connection && paramIds.indexOf(this.quarkIds_[i]) == -1) {
        connection.disconnect();
        connection.getSourceBlock().bumpNeighbours_();
      }
    }
  }
  this.arguments_ = [].concat(paramNames);
  this.argumentVarModels_ = [];
  for (var i = 0; i < this.arguments_.length; i++) {
    var variable = Blockly.Variables.getOrCreateVariablePackage(this.workspace, null, this.arguments_[i], "");
    this.argumentVarModels_.push(variable);
  }
  this.updateShape_();
  this.quarkIds_ = paramIds;
  if (this.quarkIds_) {
    for (var i = 0; i < this.arguments_.length; i++) {
      var quarkId = this.quarkIds_[i];
      if (quarkId in this.quarkConnections_) {
        var connection = this.quarkConnections_[quarkId];
        if (!Blockly.Mutator.reconnect(connection, this, "ARG" + i)) {
          delete this.quarkConnections_[quarkId];
        }
      }
    }
  }
  this.rendered = savedRendered;
  if (this.rendered) {
    this.render();
  }
}, updateShape_:function() {
  for (var i = 0; i < this.arguments_.length; i++) {
    var field = this.getField("ARGNAME" + i);
    if (field) {
      Blockly.Events.disable();
      try {
        field.setValue(this.arguments_[i]);
      } finally {
        Blockly.Events.enable();
      }
    } else {
      field = new Blockly.FieldLabel(this.arguments_[i]);
      var input = this.appendValueInput("ARG" + i).setAlign(Blockly.ALIGN_RIGHT).appendField(field, "ARGNAME" + i);
      input.init();
    }
  }
  while (this.getInput("ARG" + i)) {
    this.removeInput("ARG" + i);
    i++;
  }
  var topRow = this.getInput("TOPROW");
  if (topRow) {
    if (this.arguments_.length) {
      if (!this.getField("WITH")) {
        topRow.appendField(Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"], "WITH");
        topRow.init();
      }
    } else {
      if (this.getField("WITH")) {
        topRow.removeField("WITH");
      }
    }
  }
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("name", this.getProcedureCall());
  for (var i = 0; i < this.arguments_.length; i++) {
    var parameter = document.createElement("arg");
    parameter.setAttribute("name", this.arguments_[i]);
    container.appendChild(parameter);
  }
  return container;
}, domToMutation:function(xmlElement) {
  var name = xmlElement.getAttribute("name");
  this.renameProcedure(this.getProcedureCall(), name);
  var args = [];
  var paramIds = [];
  for (var i = 0, childNode; childNode = xmlElement.childNodes[i]; i++) {
    if (childNode.nodeName.toLowerCase() == "arg") {
      args.push(childNode.getAttribute("name"));
      paramIds.push(childNode.getAttribute("paramId"));
    }
  }
  this.setProcedureParameters_(args, paramIds);
}, getVarModels:function() {
  return this.argumentVarModels_;
}, onchange:function(event) {
  if (!this.workspace || this.workspace.isFlyout) {
    return;
  }
  if (!event.recordUndo) {
    return;
  }
  if (event.type == Blockly.Events.BLOCK_CREATE && event.ids.indexOf(this.id) != -1) {
    var name = this.getProcedureCall();
    var def = Blockly.Procedures.getDefinition(name, this.workspace);
    if (def && (def.type != this.defType_ || JSON.stringify(def.arguments_) != JSON.stringify(this.arguments_))) {
      def = null;
    }
    if (!def) {
      Blockly.Events.setGroup(event.group);
      var xml = document.createElement("xml");
      var block = document.createElement("block");
      block.setAttribute("type", this.defType_);
      var xy = this.getRelativeToSurfaceXY();
      var x = xy.x + Blockly.SNAP_RADIUS * (this.RTL ? -1 : 1);
      var y = xy.y + Blockly.SNAP_RADIUS * 2;
      block.setAttribute("x", x);
      block.setAttribute("y", y);
      var mutation = this.mutationToDom();
      block.appendChild(mutation);
      var field = document.createElement("field");
      field.setAttribute("name", "NAME");
      field.appendChild(document.createTextNode(this.getProcedureCall()));
      block.appendChild(field);
      xml.appendChild(block);
      Blockly.Xml.domToWorkspace(xml, this.workspace);
      Blockly.Events.setGroup(false);
    }
  } else {
    if (event.type == Blockly.Events.BLOCK_DELETE) {
      var name = this.getProcedureCall();
      var def = Blockly.Procedures.getDefinition(name, this.workspace);
      if (!def) {
        Blockly.Events.setGroup(event.group);
        this.dispose(true, false);
        Blockly.Events.setGroup(false);
      }
    } else {
      if (event.type == Blockly.Events.CHANGE && event.element == "disabled") {
        var name = this.getProcedureCall();
        var def = Blockly.Procedures.getDefinition(name, this.workspace);
        if (def && def.id == event.blockId) {
          var oldGroup = Blockly.Events.getGroup();
          if (oldGroup) {
            console.log("Saw an existing group while responding to a definition change");
          }
          Blockly.Events.setGroup(event.group);
          if (event.newValue) {
            this.previousDisabledState_ = this.disabled;
            this.setDisabled(true);
          } else {
            this.setDisabled(this.previousDisabledState_);
          }
          Blockly.Events.setGroup(oldGroup);
        }
      }
    }
  }
}, customContextMenu:function(options) {
  var option = {enabled:true};
  option.text = Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"];
  var name = this.getProcedureCall();
  var workspace = this.workspace;
  option.callback = function() {
    var def = Blockly.Procedures.getDefinition(name, workspace);
    if (def) {
      workspace.centerOnBlock(def.id);
      def.select();
    }
  };
  options.push(option);
}, defType_:"procedures_defnoreturn"};
Blockly.Blocks["procedures_callreturn"] = {init:function() {
  this.appendDummyInput("TOPROW").appendField("", "NAME");
  this.setOutput(true);
  this.setStyle("procedure_blocks");
  this.setHelpUrl(Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"]);
  this.arguments_ = [];
  this.quarkConnections_ = {};
  this.quarkIds_ = null;
  this.previousDisabledState_ = false;
}, getProcedureCall:Blockly.Blocks["procedures_callnoreturn"].getProcedureCall, renameProcedure:Blockly.Blocks["procedures_callnoreturn"].renameProcedure, setProcedureParameters_:Blockly.Blocks["procedures_callnoreturn"].setProcedureParameters_, updateShape_:Blockly.Blocks["procedures_callnoreturn"].updateShape_, mutationToDom:Blockly.Blocks["procedures_callnoreturn"].mutationToDom, domToMutation:Blockly.Blocks["procedures_callnoreturn"].domToMutation, getVarModels:Blockly.Blocks["procedures_callnoreturn"].getVarModels, 
onchange:Blockly.Blocks["procedures_callnoreturn"].onchange, customContextMenu:Blockly.Blocks["procedures_callnoreturn"].customContextMenu, defType_:"procedures_defreturn"};
Blockly.Blocks["procedures_ifreturn"] = {init:function() {
  this.appendValueInput("CONDITION").setCheck("Boolean").appendField(Blockly.Msg["CONTROLS_IF_MSG_IF"]);
  this.appendValueInput("VALUE").appendField(Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"]);
  this.setInputsInline(true);
  this.setPreviousStatement(true);
  this.setNextStatement(true);
  this.setStyle("procedure_blocks");
  this.setTooltip(Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"]);
  this.setHelpUrl(Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"]);
  this.hasReturnValue_ = true;
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("value", Number(this.hasReturnValue_));
  return container;
}, domToMutation:function(xmlElement) {
  var value = xmlElement.getAttribute("value");
  this.hasReturnValue_ = value == 1;
  if (!this.hasReturnValue_) {
    this.removeInput("VALUE");
    this.appendDummyInput("VALUE").appendField(Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"]);
  }
}, onchange:function() {
  if (!this.workspace.isDragging || this.workspace.isDragging()) {
    return;
  }
  var legal = false;
  var block = this;
  do {
    if (this.FUNCTION_TYPES.indexOf(block.type) != -1) {
      legal = true;
      break;
    }
    block = block.getSurroundParent();
  } while (block);
  if (legal) {
    if (block.type == "procedures_defnoreturn" && this.hasReturnValue_) {
      this.removeInput("VALUE");
      this.appendDummyInput("VALUE").appendField(Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"]);
      this.hasReturnValue_ = false;
    } else {
      if (block.type == "procedures_defreturn" && !this.hasReturnValue_) {
        this.removeInput("VALUE");
        this.appendValueInput("VALUE").appendField(Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"]);
        this.hasReturnValue_ = true;
      }
    }
    this.setWarningText(null);
    if (!this.isInFlyout) {
      this.setDisabled(false);
    }
  } else {
    this.setWarningText(Blockly.Msg["PROCEDURES_IFRETURN_WARNING"]);
    if (!this.isInFlyout && !this.getInheritedDisabled()) {
      this.setDisabled(true);
    }
  }
}, FUNCTION_TYPES:["procedures_defnoreturn", "procedures_defreturn"]};
goog.provide("Blockly.Blocks.texts");
goog.provide("Blockly.Constants.Text");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.Text.HUE = 160;
Blockly.defineBlocksWithJsonArray([{"type":"text", "message0":"%1", "args0":[{"type":"field_input", "name":"TEXT", "text":""}], "output":"String", "style":"text_blocks", "helpUrl":"%{BKY_TEXT_TEXT_HELPURL}", "tooltip":"%{BKY_TEXT_TEXT_TOOLTIP}", "extensions":["text_quotes", "parent_tooltip_when_inline"]}, {"type":"text_join", "message0":"", "output":"String", "style":"text_blocks", "helpUrl":"%{BKY_TEXT_JOIN_HELPURL}", "tooltip":"%{BKY_TEXT_JOIN_TOOLTIP}", "mutator":"text_join_mutator"}, {"type":"text_create_join_container", 
"message0":"%{BKY_TEXT_CREATE_JOIN_TITLE_JOIN} %1 %2", "args0":[{"type":"input_dummy"}, {"type":"input_statement", "name":"STACK"}], "style":"text_blocks", "tooltip":"%{BKY_TEXT_CREATE_JOIN_TOOLTIP}", "enableContextMenu":false}, {"type":"text_create_join_item", "message0":"%{BKY_TEXT_CREATE_JOIN_ITEM_TITLE_ITEM}", "previousStatement":null, "nextStatement":null, "style":"text_blocks", "tooltip":"%{BKY_TEXT_CREATE_JOIN_ITEM_TOOLTIP}", "enableContextMenu":false}, {"type":"text_append", "message0":"%{BKY_TEXT_APPEND_TITLE}", 
"args0":[{"type":"field_variable", "name":"VAR", "variable":"%{BKY_TEXT_APPEND_VARIABLE}"}, {"type":"input_value", "name":"TEXT"}], "previousStatement":null, "nextStatement":null, "style":"text_blocks", "extensions":["text_append_tooltip"]}, {"type":"text_length", "message0":"%{BKY_TEXT_LENGTH_TITLE}", "args0":[{"type":"input_value", "name":"VALUE", "check":["String", "Array"]}], "output":"Number", "style":"text_blocks", "tooltip":"%{BKY_TEXT_LENGTH_TOOLTIP}", "helpUrl":"%{BKY_TEXT_LENGTH_HELPURL}"}, 
{"type":"text_isEmpty", "message0":"%{BKY_TEXT_ISEMPTY_TITLE}", "args0":[{"type":"input_value", "name":"VALUE", "check":["String", "Array"]}], "output":"Boolean", "style":"text_blocks", "tooltip":"%{BKY_TEXT_ISEMPTY_TOOLTIP}", "helpUrl":"%{BKY_TEXT_ISEMPTY_HELPURL}"}, {"type":"text_indexOf", "message0":"%{BKY_TEXT_INDEXOF_TITLE}", "args0":[{"type":"input_value", "name":"VALUE", "check":"String"}, {"type":"field_dropdown", "name":"END", "options":[["%{BKY_TEXT_INDEXOF_OPERATOR_FIRST}", "FIRST"], ["%{BKY_TEXT_INDEXOF_OPERATOR_LAST}", 
"LAST"]]}, {"type":"input_value", "name":"FIND", "check":"String"}], "output":"Number", "style":"text_blocks", "helpUrl":"%{BKY_TEXT_INDEXOF_HELPURL}", "inputsInline":true, "extensions":["text_indexOf_tooltip"]}, {"type":"text_charAt", "message0":"%{BKY_TEXT_CHARAT_TITLE}", "args0":[{"type":"input_value", "name":"VALUE", "check":"String"}, {"type":"field_dropdown", "name":"WHERE", "options":[["%{BKY_TEXT_CHARAT_FROM_START}", "FROM_START"], ["%{BKY_TEXT_CHARAT_FROM_END}", "FROM_END"], ["%{BKY_TEXT_CHARAT_FIRST}", 
"FIRST"], ["%{BKY_TEXT_CHARAT_LAST}", "LAST"], ["%{BKY_TEXT_CHARAT_RANDOM}", "RANDOM"]]}], "output":"String", "style":"text_blocks", "helpUrl":"%{BKY_TEXT_CHARAT_HELPURL}", "inputsInline":true, "mutator":"text_charAt_mutator"}]);
Blockly.Blocks["text_getSubstring"] = {init:function() {
  this["WHERE_OPTIONS_1"] = [[Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"], "FROM_START"], [Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"], "FROM_END"], [Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"], "FIRST"]];
  this["WHERE_OPTIONS_2"] = [[Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"], "FROM_START"], [Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"], "FROM_END"], [Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"], "LAST"]];
  this.setHelpUrl(Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"]);
  this.setStyle("text_blocks");
  this.appendValueInput("STRING").setCheck("String").appendField(Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"]);
  this.appendDummyInput("AT1");
  this.appendDummyInput("AT2");
  if (Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"]) {
    this.appendDummyInput("TAIL").appendField(Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"]);
  }
  this.setInputsInline(true);
  this.setOutput(true, "String");
  this.updateAt_(1, true);
  this.updateAt_(2, true);
  this.setTooltip(Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"]);
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  var isAt1 = this.getInput("AT1").type == Blockly.INPUT_VALUE;
  container.setAttribute("at1", isAt1);
  var isAt2 = this.getInput("AT2").type == Blockly.INPUT_VALUE;
  container.setAttribute("at2", isAt2);
  return container;
}, domToMutation:function(xmlElement) {
  var isAt1 = xmlElement.getAttribute("at1") == "true";
  var isAt2 = xmlElement.getAttribute("at2") == "true";
  this.updateAt_(1, isAt1);
  this.updateAt_(2, isAt2);
}, updateAt_:function(n, isAt) {
  this.removeInput("AT" + n);
  this.removeInput("ORDINAL" + n, true);
  if (isAt) {
    this.appendValueInput("AT" + n).setCheck("Number");
    if (Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]) {
      this.appendDummyInput("ORDINAL" + n).appendField(Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]);
    }
  } else {
    this.appendDummyInput("AT" + n);
  }
  if (n == 2 && Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"]) {
    this.removeInput("TAIL", true);
    this.appendDummyInput("TAIL").appendField(Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"]);
  }
  var menu = new Blockly.FieldDropdown(this["WHERE_OPTIONS_" + n], function(value) {
    var newAt = value == "FROM_START" || value == "FROM_END";
    if (newAt != isAt) {
      var block = this.sourceBlock_;
      block.updateAt_(n, newAt);
      block.setFieldValue(value, "WHERE" + n);
      return null;
    }
    return undefined;
  });
  this.getInput("AT" + n).appendField(menu, "WHERE" + n);
  if (n == 1) {
    this.moveInputBefore("AT1", "AT2");
    if (this.getInput("ORDINAL1")) {
      this.moveInputBefore("ORDINAL1", "AT2");
    }
  }
}};
Blockly.Blocks["text_changeCase"] = {init:function() {
  var OPERATORS = [[Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"], "UPPERCASE"], [Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"], "LOWERCASE"], [Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"], "TITLECASE"]];
  this.setHelpUrl(Blockly.Msg["TEXT_CHANGECASE_HELPURL"]);
  this.setStyle("text_blocks");
  this.appendValueInput("TEXT").setCheck("String").appendField(new Blockly.FieldDropdown(OPERATORS), "CASE");
  this.setOutput(true, "String");
  this.setTooltip(Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"]);
}};
Blockly.Blocks["text_trim"] = {init:function() {
  var OPERATORS = [[Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"], "BOTH"], [Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"], "LEFT"], [Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"], "RIGHT"]];
  this.setHelpUrl(Blockly.Msg["TEXT_TRIM_HELPURL"]);
  this.setStyle("text_blocks");
  this.appendValueInput("TEXT").setCheck("String").appendField(new Blockly.FieldDropdown(OPERATORS), "MODE");
  this.setOutput(true, "String");
  this.setTooltip(Blockly.Msg["TEXT_TRIM_TOOLTIP"]);
}};
Blockly.Blocks["text_print"] = {init:function() {
  this.jsonInit({"message0":Blockly.Msg["TEXT_PRINT_TITLE"], "args0":[{"type":"input_value", "name":"TEXT"}], "previousStatement":null, "nextStatement":null, "style":"text_blocks", "tooltip":Blockly.Msg["TEXT_PRINT_TOOLTIP"], "helpUrl":Blockly.Msg["TEXT_PRINT_HELPURL"]});
}};
Blockly.Blocks["text_prompt_ext"] = {init:function() {
  var TYPES = [[Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"], "TEXT"], [Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"], "NUMBER"]];
  this.setHelpUrl(Blockly.Msg["TEXT_PROMPT_HELPURL"]);
  this.setStyle("text_blocks");
  var thisBlock = this;
  var dropdown = new Blockly.FieldDropdown(TYPES, function(newOp) {
    thisBlock.updateType_(newOp);
  });
  this.appendValueInput("TEXT").appendField(dropdown, "TYPE");
  this.setOutput(true, "String");
  this.setTooltip(function() {
    return thisBlock.getFieldValue("TYPE") == "TEXT" ? Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] : Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"];
  });
}, updateType_:function(newOp) {
  this.outputConnection.setCheck(newOp == "NUMBER" ? "Number" : "String");
}, mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("type", this.getFieldValue("TYPE"));
  return container;
}, domToMutation:function(xmlElement) {
  this.updateType_(xmlElement.getAttribute("type"));
}};
Blockly.Blocks["text_prompt"] = {init:function() {
  this.mixin(Blockly.Constants.Text.QUOTE_IMAGE_MIXIN);
  var TYPES = [[Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"], "TEXT"], [Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"], "NUMBER"]];
  var thisBlock = this;
  this.setHelpUrl(Blockly.Msg["TEXT_PROMPT_HELPURL"]);
  this.setStyle("text_blocks");
  var dropdown = new Blockly.FieldDropdown(TYPES, function(newOp) {
    thisBlock.updateType_(newOp);
  });
  this.appendDummyInput().appendField(dropdown, "TYPE").appendField(this.newQuote_(true)).appendField(new Blockly.FieldTextInput(""), "TEXT").appendField(this.newQuote_(false));
  this.setOutput(true, "String");
  this.setTooltip(function() {
    return thisBlock.getFieldValue("TYPE") == "TEXT" ? Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] : Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"];
  });
}, updateType_:Blockly.Blocks["text_prompt_ext"].updateType_, mutationToDom:Blockly.Blocks["text_prompt_ext"].mutationToDom, domToMutation:Blockly.Blocks["text_prompt_ext"].domToMutation};
Blockly.Blocks["text_count"] = {init:function() {
  this.jsonInit({"message0":Blockly.Msg["TEXT_COUNT_MESSAGE0"], "args0":[{"type":"input_value", "name":"SUB", "check":"String"}, {"type":"input_value", "name":"TEXT", "check":"String"}], "output":"Number", "inputsInline":true, "style":"text_blocks", "tooltip":Blockly.Msg["TEXT_COUNT_TOOLTIP"], "helpUrl":Blockly.Msg["TEXT_COUNT_HELPURL"]});
}};
Blockly.Blocks["text_replace"] = {init:function() {
  this.jsonInit({"message0":Blockly.Msg["TEXT_REPLACE_MESSAGE0"], "args0":[{"type":"input_value", "name":"FROM", "check":"String"}, {"type":"input_value", "name":"TO", "check":"String"}, {"type":"input_value", "name":"TEXT", "check":"String"}], "output":"String", "inputsInline":true, "style":"text_blocks", "tooltip":Blockly.Msg["TEXT_REPLACE_TOOLTIP"], "helpUrl":Blockly.Msg["TEXT_REPLACE_HELPURL"]});
}};
Blockly.Blocks["text_reverse"] = {init:function() {
  this.jsonInit({"message0":Blockly.Msg["TEXT_REVERSE_MESSAGE0"], "args0":[{"type":"input_value", "name":"TEXT", "check":"String"}], "output":"String", "inputsInline":true, "style":"text_blocks", "tooltip":Blockly.Msg["TEXT_REVERSE_TOOLTIP"], "helpUrl":Blockly.Msg["TEXT_REVERSE_HELPURL"]});
}};
Blockly.Constants.Text.QUOTE_IMAGE_MIXIN = {QUOTE_IMAGE_LEFT_DATAURI:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAA" + "n0lEQVQI1z3OMa5BURSF4f/cQhAKjUQhuQmFNwGJEUi0RKN5rU7FHKhpjEH3TEMtkdBSCY" + "1EIv8r7nFX9e29V7EBAOvu7RPjwmWGH/VuF8CyN9/OAdvqIXYLvtRaNjx9mMTDyo+NjAN1" + "HNcl9ZQ5oQMM3dgDUqDo1l8DzvwmtZN7mnD+PkmLa+4mhrxVA9fRowBWmVBhFy5gYEjKMf" + "z9AylsaRRgGzvZAAAAAElFTkSuQmCC", QUOTE_IMAGE_RIGHT_DATAURI:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAA" + 
"qUlEQVQI1z3KvUpCcRiA8ef9E4JNHhI0aFEacm1o0BsI0Slx8wa8gLauoDnoBhq7DcfWhg" + "gONDmJJgqCPA7neJ7p934EOOKOnM8Q7PDElo/4x4lFb2DmuUjcUzS3URnGib9qaPNbuXvB" + "O3sGPHJDRG6fGVdMSeWDP2q99FQdFrz26Gu5Tq7dFMzUvbXy8KXeAj57cOklgA+u1B5Aos" + "lLtGIHQMaCVnwDnADZIFIrXsoXrgAAAABJRU5ErkJggg==", QUOTE_IMAGE_WIDTH:12, QUOTE_IMAGE_HEIGHT:12, quoteField_:function(fieldName) {
  for (var i = 0, input; input = this.inputList[i]; i++) {
    for (var j = 0, field; field = input.fieldRow[j]; j++) {
      if (fieldName == field.name) {
        input.insertFieldAt(j, this.newQuote_(true));
        input.insertFieldAt(j + 2, this.newQuote_(false));
        return;
      }
    }
  }
  console.warn('field named "' + fieldName + '" not found in ' + this.toDevString());
}, newQuote_:function(open) {
  var isLeft = this.RTL ? !open : open;
  var dataUri = isLeft ? this.QUOTE_IMAGE_LEFT_DATAURI : this.QUOTE_IMAGE_RIGHT_DATAURI;
  return new Blockly.FieldImage(dataUri, this.QUOTE_IMAGE_WIDTH, this.QUOTE_IMAGE_HEIGHT, isLeft ? "\u201c" : "\u201d");
}};
Blockly.Constants.Text.TEXT_QUOTES_EXTENSION = function() {
  this.mixin(Blockly.Constants.Text.QUOTE_IMAGE_MIXIN);
  this.quoteField_("TEXT");
};
Blockly.Constants.Text.TEXT_JOIN_MUTATOR_MIXIN = {mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("items", this.itemCount_);
  return container;
}, domToMutation:function(xmlElement) {
  this.itemCount_ = parseInt(xmlElement.getAttribute("items"), 10);
  this.updateShape_();
}, decompose:function(workspace) {
  var containerBlock = workspace.newBlock("text_create_join_container");
  containerBlock.initSvg();
  var connection = containerBlock.getInput("STACK").connection;
  for (var i = 0; i < this.itemCount_; i++) {
    var itemBlock = workspace.newBlock("text_create_join_item");
    itemBlock.initSvg();
    connection.connect(itemBlock.previousConnection);
    connection = itemBlock.nextConnection;
  }
  return containerBlock;
}, compose:function(containerBlock) {
  var itemBlock = containerBlock.getInputTargetBlock("STACK");
  var connections = [];
  while (itemBlock) {
    connections.push(itemBlock.valueConnection_);
    itemBlock = itemBlock.nextConnection && itemBlock.nextConnection.targetBlock();
  }
  for (var i = 0; i < this.itemCount_; i++) {
    var connection = this.getInput("ADD" + i).connection.targetConnection;
    if (connection && connections.indexOf(connection) == -1) {
      connection.disconnect();
    }
  }
  this.itemCount_ = connections.length;
  this.updateShape_();
  for (var i = 0; i < this.itemCount_; i++) {
    Blockly.Mutator.reconnect(connections[i], this, "ADD" + i);
  }
}, saveConnections:function(containerBlock) {
  var itemBlock = containerBlock.getInputTargetBlock("STACK");
  var i = 0;
  while (itemBlock) {
    var input = this.getInput("ADD" + i);
    itemBlock.valueConnection_ = input && input.connection.targetConnection;
    i++;
    itemBlock = itemBlock.nextConnection && itemBlock.nextConnection.targetBlock();
  }
}, updateShape_:function() {
  if (this.itemCount_ && this.getInput("EMPTY")) {
    this.removeInput("EMPTY");
  } else {
    if (!this.itemCount_ && !this.getInput("EMPTY")) {
      this.appendDummyInput("EMPTY").appendField(this.newQuote_(true)).appendField(this.newQuote_(false));
    }
  }
  for (var i = 0; i < this.itemCount_; i++) {
    if (!this.getInput("ADD" + i)) {
      var input = this.appendValueInput("ADD" + i);
      if (i == 0) {
        input.appendField(Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"]);
      }
    }
  }
  while (this.getInput("ADD" + i)) {
    this.removeInput("ADD" + i);
    i++;
  }
}};
Blockly.Constants.Text.TEXT_JOIN_EXTENSION = function() {
  this.mixin(Blockly.Constants.Text.QUOTE_IMAGE_MIXIN);
  this.itemCount_ = 2;
  this.updateShape_();
  this.setMutator(new Blockly.Mutator(["text_create_join_item"]));
};
Blockly.Extensions.register("text_append_tooltip", Blockly.Extensions.buildTooltipWithFieldText("%{BKY_TEXT_APPEND_TOOLTIP}", "VAR"));
Blockly.Constants.Text.TEXT_INDEXOF_TOOLTIP_EXTENSION = function() {
  var thisBlock = this;
  this.setTooltip(function() {
    return Blockly.Msg["TEXT_INDEXOF_TOOLTIP"].replace("%1", thisBlock.workspace.options.oneBasedIndex ? "0" : "-1");
  });
};
Blockly.Constants.Text.TEXT_CHARAT_MUTATOR_MIXIN = {mutationToDom:function() {
  var container = document.createElement("mutation");
  container.setAttribute("at", !!this.isAt_);
  return container;
}, domToMutation:function(xmlElement) {
  var isAt = xmlElement.getAttribute("at") != "false";
  this.updateAt_(isAt);
}, updateAt_:function(isAt) {
  this.removeInput("AT", true);
  this.removeInput("ORDINAL", true);
  if (isAt) {
    this.appendValueInput("AT").setCheck("Number");
    if (Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]) {
      this.appendDummyInput("ORDINAL").appendField(Blockly.Msg["ORDINAL_NUMBER_SUFFIX"]);
    }
  }
  if (Blockly.Msg["TEXT_CHARAT_TAIL"]) {
    this.removeInput("TAIL", true);
    this.appendDummyInput("TAIL").appendField(Blockly.Msg["TEXT_CHARAT_TAIL"]);
  }
  this.isAt_ = isAt;
}};
Blockly.Constants.Text.TEXT_CHARAT_EXTENSION = function() {
  var dropdown = this.getField("WHERE");
  dropdown.setValidator(function(value) {
    var newAt = value == "FROM_START" || value == "FROM_END";
    if (newAt != this.isAt_) {
      var block = this.sourceBlock_;
      block.updateAt_(newAt);
      block.setFieldValue(value, "WHERE");
      return null;
    }
    return undefined;
  });
  this.updateAt_(true);
  var thisBlock = this;
  this.setTooltip(function() {
    var where = thisBlock.getFieldValue("WHERE");
    var tooltip = Blockly.Msg["TEXT_CHARAT_TOOLTIP"];
    if (where == "FROM_START" || where == "FROM_END") {
      var msg = where == "FROM_START" ? Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] : Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"];
      if (msg) {
        tooltip += "  " + msg.replace("%1", thisBlock.workspace.options.oneBasedIndex ? "#1" : "#0");
      }
    }
    return tooltip;
  });
};
Blockly.Extensions.register("text_indexOf_tooltip", Blockly.Constants.Text.TEXT_INDEXOF_TOOLTIP_EXTENSION);
Blockly.Extensions.register("text_quotes", Blockly.Constants.Text.TEXT_QUOTES_EXTENSION);
Blockly.Extensions.registerMutator("text_join_mutator", Blockly.Constants.Text.TEXT_JOIN_MUTATOR_MIXIN, Blockly.Constants.Text.TEXT_JOIN_EXTENSION);
Blockly.Extensions.registerMutator("text_charAt_mutator", Blockly.Constants.Text.TEXT_CHARAT_MUTATOR_MIXIN, Blockly.Constants.Text.TEXT_CHARAT_EXTENSION);
goog.provide("Blockly.Blocks.variables");
goog.provide("Blockly.Constants.Variables");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.Variables.HUE = 330;
Blockly.defineBlocksWithJsonArray([{"type":"variables_get", "message0":"%1", "args0":[{"type":"field_variable", "name":"VAR", "variable":"%{BKY_VARIABLES_DEFAULT_NAME}"}], "output":null, "style":"variable_blocks", "helpUrl":"%{BKY_VARIABLES_GET_HELPURL}", "tooltip":"%{BKY_VARIABLES_GET_TOOLTIP}", "extensions":["contextMenu_variableSetterGetter"]}, {"type":"variables_set", "message0":"%{BKY_VARIABLES_SET}", "args0":[{"type":"field_variable", "name":"VAR", "variable":"%{BKY_VARIABLES_DEFAULT_NAME}"}, 
{"type":"input_value", "name":"VALUE"}], "previousStatement":null, "nextStatement":null, "style":"variable_blocks", "tooltip":"%{BKY_VARIABLES_SET_TOOLTIP}", "helpUrl":"%{BKY_VARIABLES_SET_HELPURL}", "extensions":["contextMenu_variableSetterGetter"]}]);
Blockly.Constants.Variables.CUSTOM_CONTEXT_MENU_VARIABLE_GETTER_SETTER_MIXIN = {customContextMenu:function(options) {
  if (!this.isInFlyout) {
    if (this.type == "variables_get") {
      var opposite_type = "variables_set";
      var contextMenuMsg = Blockly.Msg["VARIABLES_GET_CREATE_SET"];
    } else {
      var opposite_type = "variables_get";
      var contextMenuMsg = Blockly.Msg["VARIABLES_SET_CREATE_GET"];
    }
    var option = {enabled:this.workspace.remainingCapacity() > 0};
    var name = this.getField("VAR").getText();
    option.text = contextMenuMsg.replace("%1", name);
    var xmlField = document.createElement("field");
    xmlField.setAttribute("name", "VAR");
    xmlField.appendChild(document.createTextNode(name));
    var xmlBlock = document.createElement("block");
    xmlBlock.setAttribute("type", opposite_type);
    xmlBlock.appendChild(xmlField);
    option.callback = Blockly.ContextMenu.callbackFactory(this, xmlBlock);
    options.push(option);
  } else {
    if (this.type == "variables_get" || this.type == "variables_get_reporter") {
      var renameOption = {text:Blockly.Msg.RENAME_VARIABLE, enabled:true, callback:Blockly.Constants.Variables.RENAME_OPTION_CALLBACK_FACTORY(this)};
      var name = this.getField("VAR").getText();
      var deleteOption = {text:Blockly.Msg.DELETE_VARIABLE.replace("%1", name), enabled:true, callback:Blockly.Constants.Variables.DELETE_OPTION_CALLBACK_FACTORY(this)};
      options.unshift(renameOption);
      options.unshift(deleteOption);
    }
  }
}};
Blockly.Constants.Variables.RENAME_OPTION_CALLBACK_FACTORY = function(block) {
  return function() {
    var workspace = block.workspace;
    var variable = block.getField("VAR").getVariable();
    Blockly.Variables.renameVariable(workspace, variable);
  };
};
Blockly.Constants.Variables.DELETE_OPTION_CALLBACK_FACTORY = function(block) {
  return function() {
    var workspace = block.workspace;
    var variable = block.getField("VAR").getVariable();
    workspace.deleteVariableById(variable.getId());
    workspace.refreshToolboxSelection();
  };
};
Blockly.Extensions.registerMixin("contextMenu_variableSetterGetter", Blockly.Constants.Variables.CUSTOM_CONTEXT_MENU_VARIABLE_GETTER_SETTER_MIXIN);

goog.provide("Blockly.Constants.VariablesDynamic");
goog.require("Blockly.Blocks");
goog.require("Blockly");
Blockly.Constants.VariablesDynamic.HUE = 310;
Blockly.defineBlocksWithJsonArray([{"type":"variables_get_dynamic", "message0":"%1", "args0":[{"type":"field_variable", "name":"VAR", "variable":"%{BKY_VARIABLES_DEFAULT_NAME}"}], "output":null, "style":"variable_dynamic_blocks", "helpUrl":"%{BKY_VARIABLES_GET_HELPURL}", "tooltip":"%{BKY_VARIABLES_GET_TOOLTIP}", "extensions":["contextMenu_variableDynamicSetterGetter"]}, {"type":"variables_set_dynamic", "message0":"%{BKY_VARIABLES_SET}", "args0":[{"type":"field_variable", "name":"VAR", "variable":"%{BKY_VARIABLES_DEFAULT_NAME}"}, 
{"type":"input_value", "name":"VALUE"}], "previousStatement":null, "nextStatement":null, "style":"variable_dynamic_blocks", "tooltip":"%{BKY_VARIABLES_SET_TOOLTIP}", "helpUrl":"%{BKY_VARIABLES_SET_HELPURL}", "extensions":["contextMenu_variableDynamicSetterGetter"]}]);
Blockly.Constants.VariablesDynamic.CUSTOM_CONTEXT_MENU_VARIABLE_GETTER_SETTER_MIXIN = {customContextMenu:function(options) {
  if (!this.isInFlyout) {
    var opposite_type;
    var contextMenuMsg;
    var id = this.getFieldValue("VAR");
    var variableModel = this.workspace.getVariableById(id);
    var varType = variableModel.type;
    if (this.type == "variables_get_dynamic") {
      opposite_type = "variables_set_dynamic";
      contextMenuMsg = Blockly.Msg["VARIABLES_GET_CREATE_SET"];
    } else {
      opposite_type = "variables_get_dynamic";
      contextMenuMsg = Blockly.Msg["VARIABLES_SET_CREATE_GET"];
    }
    var option = {enabled:this.workspace.remainingCapacity() > 0};
    var name = this.getField("VAR").getText();
    option.text = contextMenuMsg.replace("%1", name);
    var xmlField = document.createElement("field");
    xmlField.setAttribute("name", "VAR");
    xmlField.setAttribute("variabletype", varType);
    xmlField.appendChild(document.createTextNode(name));
    var xmlBlock = document.createElement("block");
    xmlBlock.setAttribute("type", opposite_type);
    xmlBlock.appendChild(xmlField);
    option.callback = Blockly.ContextMenu.callbackFactory(this, xmlBlock);
    options.push(option);
  } else {
    if (this.type == "variables_get_dynamic" || this.type == "variables_get_reporter_dynamic") {
      var renameOption = {text:Blockly.Msg.RENAME_VARIABLE, enabled:true, callback:Blockly.Constants.Variables.RENAME_OPTION_CALLBACK_FACTORY(this)};
      var name = this.getField("VAR").getText();
      var deleteOption = {text:Blockly.Msg.DELETE_VARIABLE.replace("%1", name), enabled:true, callback:Blockly.Constants.Variables.DELETE_OPTION_CALLBACK_FACTORY(this)};
      options.unshift(renameOption);
      options.unshift(deleteOption);
    }
  }
}, onchange:function() {
  var id = this.getFieldValue("VAR");
  var variableModel = this.workspace.getVariableById(id);
  if (this.type == "variables_get_dynamic") {
    this.outputConnection.setCheck(variableModel.type);
  } else {
    this.getInput("VALUE").connection.setCheck(variableModel.type);
  }
}};
Blockly.Constants.VariablesDynamic.RENAME_OPTION_CALLBACK_FACTORY = function(block) {
  return function() {
    var workspace = block.workspace;
    var variable = block.getField("VAR").getVariable();
    Blockly.Variables.renameVariable(workspace, variable);
  };
};
Blockly.Constants.VariablesDynamic.DELETE_OPTION_CALLBACK_FACTORY = function(block) {
  return function() {
    var workspace = block.workspace;
    var variable = block.getField("VAR").getVariable();
    workspace.deleteVariableById(variable.getId());
    workspace.refreshToolboxSelection();
  };
};
Blockly.Extensions.registerMixin("contextMenu_variableDynamicSetterGetter", Blockly.Constants.VariablesDynamic.CUSTOM_CONTEXT_MENU_VARIABLE_GETTER_SETTER_MIXIN);
return Blockly.Blocks;
        }